### ISSUE TITLE
Choose most optimal ordered DS for tlog blocks

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#164]
Since PR #161 we use https://godoc.org/github.com/emirpasic/gods/sets/treeset as the data structure of choice to order our cached blocks, based on their `sequence : int64`. However:

> "There is no strong reason to use this package yet, there are actually many packages out there and we need to benchmark them to get the best package." - @iwanbk, issue #143 

Perhaps it turns out that the current treeset is the most optimal, but perhaps not.

A follow up question is also if we even require a set in order to filter duplicate messages. In theory I don't think it will matter, as we already know if 2 members are equal based on the comparison check (as its result will be `0`). But this question should be answered, such that we can benchmark in a fair way (such that all data structures which we benchmark have the same rules (eg removing duplicates).

**Comment by iwanbk** [comment]
i dont this kind of optimization should be in 1.1.0-alpha-3 milestone.

**Comment by GlenDC** [comment]
Roger that, not sure who decides these milestones, but switched it to alpha-4.

**Comment by iwanbk** [comment]
This data structure is not used anymore since #484
