### ISSUE TITLE
zeroctl: delete legacy copy/delete nondeduped/deduped commands

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#205]
In issue #204 we added 2 new commands:

+ `g8stor copy vdisk`;
+ `g8stor delete vdisks`;

They were additional commands in previous milestone, but are now fully replacing the old (legacy) commands:

+ `g8stor copy deduped`;
+ `g8stor copy nondeduped`;
+ `g8stor delete deduped`;
+ `g8stor delete nondeduped`;

These 4 legacy commands should now be deleted, as their usage is highly error prone, and non-usable for most of our use cases.

**Comment by robvanmieghem** [comment]
@grimpy Can you let us know when this has been changed so we don't break the existing setups?

**Comment by robvanmieghem** [comment]
@iwanbk @GlenDC Since we are in a new milestone, I think we can safely do this now
