### ISSUE TITLE
zeroctl: make copy nondeduped vdisks work with len(targetServers) != len(sourceServers)

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#206]
Because the way that data is written over multiple (data) ardbs,
the `zeroctl copy vdisk` command, will produce an incorrect result when copying data (which is spread across multiple data storage servers)
simply by manipulating the ardb directly, in the naive way that it is done now, in the case that the length of the source and target servers is not the same.

It could be supported, by writing it to ardbs using the same spreading algorithm as that the nbdserver uses.

**Comment by GlenDC** [comment]
We can probably move this to a future milestone, when the rebalancing/re-spreading algorithm is implemented, as this command's scenario in question will want to use a similar re-spreading algorithm.

**Comment by GlenDC** [comment]
Originally this was only a problem with non-deduped vdisks. But it is now also a problem (because of #306) with deduped vdisks. So it applies to all vdisks now.

**Comment by iwanbk** [comment]
@zaibon 
as part of our work, i began to create the test, the test doesn't really work now.
Plase see the NOTES part,  it contains the clue to make it work, i hope the clue is usefull

https://gist.github.com/iwanbk/a41c5f9049d31871e54c893abebd6cdc#file-deduped_copy_test-go-L22-L29

**Comment by GlenDC** [comment]
I've now split this issue in two issues, so that this issue can once again be talking just about non-deduped vdisks as was originally the case (even though the title was originally wrong and was talking about deduped vdisks).

A new issue #503 has been created to fix the issue for deduped vdisks, and will be resolved based on the research done by @zaibon.
