### ISSUE TITLE
rename repo and relevant code/dependencies from blockstor to zerodisk

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#212]
Product has to be renamed from `g8os/blockstor` to `Zero-OS/zerodisk`. This will also have to be reflected in the documentation, import code, and any other code (inline comments, names, ...).

**Comment by GlenDC** [comment]
`g8stor` will also have to be renamed. Could be as simple as `zeroctl`, but I guess you already have names in mind @grimpy and @robvanmieghem.

**Comment by robvanmieghem** [comment]
Fixed by f45cce856550de28d2edf0d1cf9c2d673f5da462
