### ISSUE TITLE
Add and support "tmp" vdisk type

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#217]

**Comment by robvanmieghem** [comment]
The original thought was to have tmp disk as local qcow files and not have them go over the nbdserver. This however was way more complex and it's easier if the tmp disks do run over the nbdserver when setting up such a vm. The current implementation creates a cache disk and then uses the g8stor command to delete it later. I do think supporting the tmp disk in the configfile is a good thing but nothing special needs to be done besids that.

**Comment by GlenDC** [comment]
> though I think the functionality you described seems usefull as well, even though not needed immediately. Created issue #222 for it and put it on milestone roadmap.

Supporting and thus resolving that issue would only require 5 mins time though, as the storage type is already implemented and used for testing purposes (of the `tlogstorage`)
