### ISSUE TITLE
Add and support "memory" vdisk storage type

### ISSUE THREAD

**Issue by robvanmieghem** [zero-os/0-Disk#222]
| Disk type | Redundant | Persistent | Template Support | Rollback | Performance Optimized |
| --------- | --------- | ---------- | ---------------- | -------- | --------------------- |
| memory | no | no | no | no | yes |

Not sure what `performance optimized` means in this context.

However the rest of the information seems that we could simply use the newly added `InMemoryStorage` for this. A simple pure-go in-memory storage implementation to be found here: [nbdserver/ardb/inmemory.go](https://github.com/g8os/blockstor/blob/e023bb00a9c3d0f796efb323e1d53c83f9b10352/nbdserver/ardb/inmemory.go).

It's a vdisk that will lose its content as soon as the user disconnects from the nbdserver, which I think is what `persistent` means in this context.

It doesn't support`rollback`, meaning we won't be using it in combination with the `tlog- storage/server/client`.

So with that knowledge in mind, we simply have to:

+ add the `memory` vdisk type to the config code, such that it can be used from the configuration files;
+ add a new `memory` storage type, that for now only will be used for the `memory` vdisk type;
+ add a new switch case for the `memory` storage type in the `ardb.go` code, where we create the `inMemoryStorage`, for such vdisks that have the `memory` storage type;
+ add unit-test code that reflect these changes;

**Comment by GlenDC** [comment]
Not required by any project and never formally specified.
