### ISSUE TITLE
tlogclient : Filter out io.EOF error 

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#226]
Possible bug was reported at https://github.com/g8os/blockstor/pull/209#issuecomment-305367738

**Comment by GlenDC** [comment]
Perhaps you know better with your inside (tlog) knowledge, but isn't the `data hash is incorrect` message the bigger possible bug reported in that comment?

**Comment by iwanbk** [comment]
> but isn't the data hash is incorrect message the bigger possible bug reported in that comment?

Oh, not sure why i missed that part of comment when created this issue

**Comment by GlenDC** [comment]
Yeah I think that's the more important part, I don't think at that stage we should ever get an `io.EOF` error, as it means the server couldn't receive something we sent, which isn't really good at all.

Once we wound why the `data hash is incorrect` happens, we should also make a unit test for it, that 100% of the runs triggers the reason for this error, as now it's pretty hard to reproduce it.

**Comment by GlenDC** [comment]
issue #232 replaces this issue, as #232 describes the reported issue better. Panicking on an io.EOF error in that location is valid AFAIK.

**Comment by iwanbk** [comment]
from my quick check, it is indeed a bug

**Comment by GlenDC** [comment]
@iwanbk but this bug is #232 right? I don't get how the io.EOF panic is a bug, that's I think expected behavior, or am I missing something here?

**Comment by iwanbk** [comment]
The bug is : tlogclient doesn't reconnect after it's connection getting closed.

**Comment by iwanbk** [comment]
The reconnect code currently only exist in `Send` part, while we also have another goroutine that read from the  socket.
I currently have no idea to have two reconnect code in both `Send` and `Receive` part.

Another idea is to create a goroutine that do the reconnect. `Send` and `Recv` part need to send message to that goroutine in order to do reconnect.
