### ISSUE TITLE
nbdserver vdisk : try to recover when tlog connection failed

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#229]
Maybe recreate the client?

Previous discussion https://github.com/g8os/blockstor/issues/126#issuecomment-305186277

**Comment by GlenDC** [comment]
But if that fails, visible to the tlogclient user, doesn't that mean that the client already tried at least 4 time to reconnect? I think there has to be a limit on how much we try now? Clearly that means there is something bad going on with the tlogserver if we still can't connect to it after 4 retries.

**Comment by iwanbk** [comment]
>  doesn't that mean that the client already tried at least 4 time to reconnect? 

correct

> I think there has to be a limit on how much we try now? 

Correct

> Clearly that means there is something bad going on with the tlogserver if we still can't connect to it after 4 retries.

Partly correct. IMO, there might be another cases to handle:
- tlogclient just become corrupted. We don't want it to happen, but we need to prepare. 
- tlogserver might be in process of self healing

Just realized that we need to add `recover` to tlogclient

**Comment by GlenDC** [comment]
> Just realized that we need to add recover to tlogclient

What would that do?

**Comment by iwanbk** [comment]
> What would that do?

I mean `recover` function you added to tlogserver and nbdserver, perhaps it is not needed.

I think we might need to wait for #198 (or other similar issues to add redundancy to tlog server) before working on this issue.

**Comment by iwanbk** [comment]
Handled by #279
