### ISSUE TITLE
nbdserver freeze when converting big image

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#247]
When converting ubuntu image, the process couldn't be finished.
And i found that there are many too many logs/blocks in the block buffer.
Possible issues:
- bug in client's block buffer
- bug in client receiver
- bug in nbdserver's tlogStorage

**Comment by iwanbk** [comment]
There is issue in the client receiver or server response sender.
nbdserver stuck with : 
- 100K logs sent
- 12K response received

**Comment by iwanbk** [comment]
By add logging, i can see that server has no issue to send the response.
It is client that too slow to read the response.

**Comment by iwanbk** [comment]
The problem has been fixed by c91b0d2c0d41c6df558d5d3728c9b06b1e864ee3 , fix needed in both tlog and nbdserver:
- tlogclient : use socket directly to receive, instead of buffered reader -> i'm sure this is good fix
- nbdserver tlogStorage: use goroutine for flushing cached content -> still not sure if it is a good fix

**Comment by iwanbk** [comment]
spoke to soon, there is no change needed in the tlogclient, because it actually didn't use buffered reader :).

The only change needed is in the nbdserver. (which make the nbdserver test failed)
Still no idea why it needs this way.

See 1019b19b52499ecf7131a2150b693647bec00502 for the fix

**Comment by iwanbk** [comment]
7e482e84211891b48af1c1a73053d17ef8f52383 fix this issue and pass `go test -race`.

Summary of the fixes:
- use separate goroutine to flush from sequence cache to storage, named `flusher`
- re-added `storageMux`, because `flushCachedContent` do storage operation and is not under `mux` mutex

The think that bugging me is : `flusher` need very big size of channel.
I think we might still have problem somewhere else.

**Comment by iwanbk** [comment]
> The think that bugging me is : flusher need very big size of channel.
> I think we might still have problem somewhere else

I think i might found the real issue.
I saw the length of channel reach 7K, it means there are 7K tlog flush vs 0 nbdserver flush.
It seems nbdserver need to flush more often

**Comment by iwanbk** [comment]
> When converting ubuntu image

It is 1.4G image from http://kambing.ui.ac.id/iso/ubuntu/releases/16.04/ubuntu-16.04-desktop-amd64.iso

**Comment by GlenDC** [comment]
> I saw the length of channel reach 7K, it means there are 7K tlog flush vs 0 nbdserver flush.
It seems nbdserver need to flush more often

Making the nbdserver flush is as easy, as making sure the tlogserver sends the FlushOK message, no? So that would just be a matter of sending that message earlier... no?

**Comment by iwanbk** [comment]
No, 7K there means 7K FlushOK response.

**Comment by GlenDC** [comment]
> No, 7K there means 7K FlushOK response.

Oh... that seems bad, perhaps you are sending flushOK messages too quickly? I mean if you for a big image send every 25 sequences, you get to a lot of sequences very fast o.o But still I guess we need to be able to handle that?

**Comment by iwanbk** [comment]
Maybe the solution is not make the `Flush` to be more often, but make the `flusher`/`flushCachedContent` to be faster.
Not sure, need to check it again.
