### ISSUE TITLE
tlogclient : add resend and reconnect to ForceFlushAtSeq

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#256]
- [x] reconnect (#263)
- [ ] resend

**Comment by iwanbk** [comment]
The reconnect feature added at #263,

**Comment by iwanbk** [comment]
The resend feature need code addition to the blockbuffer package, which only designed to be used for block resend.

I think the better way is to make all commands to be in separate tcp connection or  use capnp rpc.
It has the advantage to not mix command with data.

**Comment by iwanbk** [comment]
Can't find a good solution for `resend` without add too much complexity to the code.
I think the best solution are:
- update the docs, states that user need to do the retry
- update nbdserver code to do the retry

**Comment by GlenDC** [comment]
That would just move the complexity rather than preventing it, no? We still write the nbdserver code, so we would simply be writing the complexity in the nbdserver code, where I'm not sure this resend code really belongs.

**Comment by iwanbk** [comment]
> That would just move the complexity rather than preventing it, no

The complexity is different, in a way that i can't solve it in a clean way in tlog client.

But yeah, your other points are right.
