### ISSUE TITLE
nbdserver tlogStorage : call Flush more often and or faster

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#258]
related to https://github.com/zero-os/0-Disk/issues/247#issuecomment-306767170
I wonder if the fix for that issue still working for bigger image.

I don't see any call to `Flush` in tlogStorage code, so the `Flush` might be called by `gonbdserver` package.

**Comment by GlenDC** [comment]
Yes `Flush` is called by the `gonbdserver` package in [/gonbdserver/nbd/connection.go#L431-L437](https://github.com/zero-os/0-Disk/blob/415d8fbedaba9aaa1958cd632c882c77ee7da8d5/gonbdserver/nbd/connection.go#L431-L437) and [/gonbdserver/nbd/connection.go#L475-L479](https://github.com/zero-os/0-Disk/blob/415d8fbedaba9aaa1958cd632c882c77ee7da8d5/gonbdserver/nbd/connection.go#L475-L479).

Not sure what you're planning with this issue. But i don't think calling `Flush` is the solution.

`ForceFlushAtSeq` (which is I guess why you are looking at the `Flush` method) should be meant as a last resort. If that's becomes your go-to method, I think there is something we might have to rethink in the design. As it shouldn't be part of the casual flow.

**Comment by iwanbk** [comment]
I added 'and or faster' to the title.

> ForceFlushAtSeq (which is I guess why you are looking at the Flush method) should be meant as a last resort.

No, `ForceFlushAtSeq` only needed when we wait for tlog's flush.
In this issue, tlog's flush is faster than nbdserver's.

What i'm looking at the `Flush` is this line `err = tls.storage.Flush() `.
Why don't we do `storage.Flush` after each tlog's flush?

**Comment by iwanbk** [comment]
> Not sure what you're planning with this issue. But i don't think calling Flush is the solution.

After reading the gonbdserver you pointed at, i think you're right.

How about make it faster? (still no idea thought)

**Comment by GlenDC** [comment]
> What i'm looking at the Flush is this line err = tls.storage.Flush(). Why don't we do storage.Flush after each tlog's flush?

Because that's not what you think it is. Also it would deviate from non-tlog vdisks, as flush is only called by the user.

For nondeduped storage, that flush function does nothing. And For deduped storage that flush function only flushes what is left in the LBA cache, which is only the last 128 shards. Which for a big image as you are converting, is probably only the last tiny portion of it.

The more important thing is writing to the storage (`Set`/`Delete`), and that does happen in each tlog's flush.

**Comment by GlenDC** [comment]
> How about make it faster? (still no idea thought)

Fairly sure that `storage.Flush` is honestly not the issue here. If it were, we would have seen that popping up before, as we have converted big images such as Windows 10 already using the dedupedStorage code.

Like I said, that `storage.Flush` function really does almost nothing.

**Comment by iwanbk** [comment]
Oh, i meant make the `flushCachedContent` (or other things that relate to it) faster.
We already have one issue for it at #251

**Comment by iwanbk** [comment]
I think the solution might be at #250, moved that issue to current milestone
