### ISSUE TITLE
Add rollback ability to vdisks

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#269]
- Ability to rollback the vidisks that to any point in time

**Comment by iwanbk** [comment]
@khaledkbadr can you add the features you want?
I imagine it must support start & end timestamp.

And what is the difference between snapshot & rollback, i think it is essentially the same, right?

**Comment by khaledkbadr** [comment]
Updated description!

**Comment by robvanmieghem** [comment]
You can recreate from the tlog, the timestampt is feature that still needs to be added:
https://github.com/zero-os/0-Disk/issues/237

**Comment by GlenDC** [comment]
Can we close this as a duplicate, because I think restoring is already supported, we just miss the timestamp feature (#237) as @robvanmieghem noted. Or is there some extra feature that this issue is describing and that I am missing?

**Comment by khaledkbadr** [comment]
Yup, it sure is a duplicate from #237
