### ISSUE TITLE
identify tlogserver's metadata with more then just the vdiskID

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#272]
Currently metadata on the tlogserver (eg `lastHash`) is identified only using using an ID following the template: `last_hash_<vdiskID>`. This is however a problem, in case machines (boot vdisks) get cloned using the `zeroctl copy vdisk` command. In that case, the copy and the original vdisk might still share the same ID, and their tlog chain would still be stored on the same servers. However, it would be a disaster if they would overwrite each others lastHash (and whatever metadata we'll have in the future), from that point on.

So when cloning a machine (boot vdisk), we really want to be able to fork the tlog chain as well. Thanks to the way that tlog aggregations are stored, this would really be super cheap, and nothing special would have to be done, as all data is stored without referencing the vdiskID. So with cheap I mean, there would be literally no cost at all.

The only place where the vdiskID is referenced is when storing metadata. So that's something we have to somehow address. This could be as simple as generating a nonce for each new vdisk (wether that's created using cloning or by starting a new vdisk). If so, we do have to store this nonce in the persistent storage of the vdisk's meta storageServer, as it would be needed in order to reference the required (lastHash) metadata.

**Comment by iwanbk** [comment]
>  This is however a problem, in case machines (boot vdisks) get cloned using the zeroctl copy vdisk command. In that case, the copy and the original vdisk might still share the same ID

I think ID must be unique and one ID must only point to single object.
If vdisk ID doesn't behave that way, we should rename it to vdisk name.
I think the correct solution is for the `copy` command to generate another id.

>  as all data is stored without referencing the vdiskID.

The aggregation object actually has `vdiskID` field. I don't know what it is for, i think we can remove it.

**Comment by iwanbk** [comment]
> I think the correct solution is for the copy command to generate another id.

From the docs, i can see that `copy` command already use other vdiskID.
So, i don't see any issue here.
We only need to add `last_hash_[new_vdiskid]`

**Comment by GlenDC** [comment]
> I think the correct solution is for the copy command to generate another id.

But he ID is chosen by the user, not generated. Also the vdisk ID is unique per storage server, yet you can have 2 vdisks at different storage servers, with the same ID, yet they would still have their tlog data on the same tlog storage servers.

> From the docs, i can see that copy command already use other vdiskID.

Nope, using another vdiskID is only required if you copy vdisks within the same storage cluster

But for example, if the config defines that deduped vdisk `a` is stored on metadata server `mycluster`, you could copy it to `othercluster`, where the clone has the same ID as the original using the following command: `$ zeroctl copy vdisk a a othercluster`

In this case you really do have an issue, as the tlogCluster might still be shared...

> The aggregation object actually has vdiskID field. I don't know what it is for, i think we can remove it.

Ah you're right, if we don't require it for anything important, than we should definitely remove it, otherwise forking would be very expensive, as we would have to copy the entire chain...

**Comment by iwanbk** [comment]
>  Also the vdisk ID is unique per storage server

Doesn't feel right for me. Because AFAIK, the `user` here is not human, but `orchestrator`, should be easy to generate something unique.

> In this case you really do have an issue, as the tlogCluster might still be shared...

I still can't see the issue, the tlog chain is immutable.
There is no problem if at some point, two vdisk ids refer to same hash

**Comment by GlenDC** [comment]
> There is no problem if at some point, two vdisk ids refer to same hash

There is no problem if two vdisk ids refer to the same hash. But there is a problem if two vdisks have the same id and thus the same reference at all times. Even though they started deviating from one another.

> Doesn't feel right for me. Because AFAIK, the user here is not human, but orchestrator, should be easy to generate something unique.

All fine for me, I don't know what the specs have to be. I have no visibility on the final roadmaps whatsoever. if what you say is true, then there is no problem. Can @robvanmieghem and/or @grimpy confirm this is indeed true? Or @iwanbk can you link me to the docs that define the desired behavior like that?

**Comment by iwanbk** [comment]
>  But there is a problem if two vdisks have the same id and thus the same reference at all times

Yeah, you're right in this case. 


> r @iwanbk can you link me to the docs that define the desired behavior like that?

No, i don't have any docs.
I'm only saying that this behavior is not a right behavior. 

How about using vdisk ID + storageCluster name?

**Comment by GlenDC** [comment]
> How about using vdisk ID + storageCluster name?

Storage cluster name has no meaning outside your local config file. It's just a name you use to reference to the addresses you mention. AFAIK there is no real definition of a storage cluster outside the realm of your config file.

**Comment by iwanbk** [comment]
Then i propose to make the vdiskID really unique, not only per storage cluster.
Other option is to make vdisk ID unique not only per storage cluster, but also per tlog server.
@robvanmieghem @grimpy

**Comment by GlenDC** [comment]
@zaibon and/or @FastGeert you probably want to chip in with this one.

**Comment by zaibon** [comment]
> Doesn't feel right for me. Because AFAIK, the user here is not human, but orchestrator, should be easy to generate something unique.

The Vdisk ID is not even choosen by the orchestrator, the name comes from the layer on top even. So the final client can creates it's own ID scheme.

**Comment by iwanbk** [comment]
> So the final client can creates it's own ID scheme.

OK, i see the problem now.

> This could be as simple as generating a nonce for each new vdisk

Did you mean add a kind of uuid for this vdisk? 

>  If so, we do have to store this nonce in the persistent storage of the vdisk's meta storageServer

A mapping from vdiskID to the nonce?

**Comment by despiegk** [comment]
- this goes together with discussion of using etcd for config mgmt & tlog server metadata.
- a vdisk needs to have a unique id (generated by AYS or any other consumer, its their role to make it unique)
- tlog's need to re-use this id for their purpose, add info can be stored in etcd

**Comment by iwanbk** [comment]
> a vdisk needs to have a unique id (generated by AYS or any other consumer, its their role to make it unique)

It seems we can close this issue

**Comment by GlenDC** [comment]
Closing this as @despiegk's solution resolved this from a top-bottom approach.

Just note that if this uniqueness can somehow be broken, you well get undefined behavior, where things might break down in a very subtle and hard to debug way, depending on how it manifest itself.
