### ISSUE TITLE
nbdserver.tlogStorage : store last flushed sequence in  metadata server

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#273]
Store last sent sequence the tlogStorage's vdisk's storageCluster's metadataServer.  This will then also be loaded when loading/starting the vdisk (if possible).

Part of #230.

**Comment by GlenDC** [comment]
WIP branch can be found @ https://github.com/zero-os/0-Disk/tree/store-tlog-last-seq.

**Comment by iwanbk** [comment]
Why we need this?

I think what important is last sequence flushed (by nbdserver & by tlog).
Last sent sequence doesn't really matter because:
- it could be lost
- tlog failed to flush it

**Comment by GlenDC** [comment]
Changed title, you're right.

>  think what important is last sequence flushed (by nbdserver & by tlog)

Does mean that when you restart the vdisk, the tlog server might have already flushed more, and so you would end up asking the tlog server anyhow what sequence its on. So storing the last flushed sequence seems not useful at all. As either it will be the same value as the server sends back, or it will be higher than we stored, either way, we'll end up wanting to use whatever think the server on is anyhow.

So perhaps storing the last flushed sequence is a stupid idea? And a better idea would be that we either:

+ get the last flushed sequence as part of the handshake response;
+ get the last flushed sequence by asking it via a command;

I think just getting it as part of the handshake response would make most sense, where for a new vdisk we would simply return the given value by the client.

But perhaps you think differently about it.

**Comment by iwanbk** [comment]
> the tlog server might have already flushed more

Yes

> So storing the last flushed sequence seems not useful at all

It is still useful.

The scenario:
- nbdserver last flushed = 10
- tlogserver last flushed = 20

How to make it synced again? Restore (using tlog replay) the sequence 11-20.

**Comment by GlenDC** [comment]
Makes sense, will adapt my WIP branch using this new knowledge, so it's ready for you.

**Comment by GlenDC** [comment]
Ok forget about any WIP made for this issue.

This issue contains 2 main tasks:

1. store the last flushed sequence (you can do this during the flush command), in _all_ data storage servers used by the tlogStorage;
2. when starting a tlogStorage (as in creating it), we would need to read those last flushed sequence back (if they exist of course). For now I would say just use whatever highest value you get (in case different storage servers have different values defined for it), but if you have a better idea on how to come to a consensus than feel free to go for that one;
3. modify the `HandshakeResponse` of the tlog handhsake protocol, so that it also returns the sequence it will use (it _should_ be the `firstSequence` given by the client in case `resetFirstSequence` is true, but it can also be a higher value in case that bool is false), obviously we than also no longer want to reset that first sequence in our tlogStorage;
4. in case the returned sequence of the server is higher than the one we had stored, you will need to use the tlog replay feature to get the vdisk up to date;

My description here is a bit rough, but I hope it gets your started working on this issue @chrisvdg.

**Comment by GlenDC** [comment]
> ...  store the last flushed sequence (you can do this during the flush command), in all data storage servers used by the tlogStorage;
> ...
> ... we would need to read those last flushed sequence back (if they exist of course)...
> ...

OK forget about the quoted stuff above @chrisvdg. Simply replicating the metadata over multiple storage servers is not a viable approach any longer. And as we might be going an entire different direction in milestone 7, just store the last flushed sequence on the metadata storage server for now. As a consequence, make sure to validate that a storage cluster used for a tlogStorage has a metadata storage server.

How we store the sequence on the tlogStorage (and thus client) side will probably (see: hopefully) change in milestone 7, but for now this will be good enough, without wasting too much time on algorithms and whatnot, that will not live that long anyhow.

**Comment by iwanbk** [comment]
> And as we might be going an entire different direction in milestone 7,

Using 0-stor-lib?

**Comment by despiegk** [comment]
moving to new architecture of 0-store, makes this one obsolete

**Comment by iwanbk** [comment]
> moving to new architecture of 0-store, makes this one obsolete

whatever way we Go (0-stor or own metadata server) we need to implement this, so i reopen this issue.

Moved it to milestone-7 because it needs 0-stor

**Comment by iwanbk** [comment]
@GlenDC @chrisvdg 

[0-stor metadata](https://github.com/zero-os/0-stor/blob/master/client/specs/metadata.md) is not suitable for this purpose and yet what we need is very simple `put` and `get` to etcd server.

I suggest we don't use 0-stor lib and just do write/read to etcd.
If nobody able to work on it, i can do it next week. Only need suggestion about how to emulate the etcd in unit test. Using stub_source like what we do in config module?

**Comment by GlenDC** [comment]
You can just define your own interface, and define a stub implementation for tests, that's definitely the way to go.

+ How would you configure the ETCD cluster to use for this?
+ In general we have to really talk and agree one of these days on how we handle copying of tlog-supported vdisks? I mean do we also copy its tlog data? And if so, do we also need to copy its metadata in this new ETCD cluster?

I suggest you work on this, yes. Should be fairly simple the way you describe it. Its complications are less clear to me at the moment however.

**Comment by iwanbk** [comment]
> How would you configure the ETCD cluster to use for this?

I don't get your question. I mean, it is the orchestrator responsibility to deploy it, no?

Or do you mean the key prefix? How config module do the prefixing?

> In general we have to really talk and agree one of these days on how we handle copying of tlog-supported vdisks? I mean do we also copy its tlog data? And if so, do we also need to copy its metadata in this new ETCD cluster?

I think it deserve separate issue as we really need to think about it.

**Comment by GlenDC** [comment]
It deploys an ETCD cluster for configuration, it's not used for anything else. And no the prefixing I am not talking about that. I am merely talking about the fact where you'll configure the ETCD cluster, as in how will the tlog storage have the server information it requires to start pushing data, and where does the cluster come from.

It could be orchestrator responsibility, but that doesn't just happen, that would need discussion with Jo and Christophe.

**Comment by iwanbk** [comment]
Could you elaborate more? Maybe give your idea about this matter.

>  as in how will the tlog storage have the server information it requires to start pushing data

from tlogStorage point of view, of course it gets the etcd address from the config module, or more precise just an argument in it's constructor

**Comment by GlenDC** [comment]
Why would we store this  in etcd, why not simply use ARDB like we do for all the other storage purposes. I don't see why you're making a special case out of this?

**Comment by iwanbk** [comment]
https://github.com/zero-os/0-Disk/issues/273#issuecomment-314017132

> moving to new architecture of 0-store, makes this one obsolete

I think the reason is the same as why we move tlog metadata server from ardb to etcd.
I thought you know the reason better than me because the decision was taken while i'm in vacation.

I think it is indeed better to move to etcd because etcd already provide redundancy.

**Comment by GlenDC** [comment]
Sure but this is just about some metadata for the storage side. Which makes this an exception. On top of that it's not like this value is that important that we would care too much if we would lose it, it would just mean we would have to trust the server, which shouldn't really be an issue anyhow?

**Comment by iwanbk** [comment]
> On top of that it's not like this value is that important that we would care too much if we would lose it

It is absolutely important if we want to implement #230

**Comment by GlenDC** [comment]
@iwanbk I suppose we would store this in the same etcd as used for 0-stor and configured in https://github.com/zero-os/0-Disk/blob/master/docs/config.md#zerostorclusterconfig (metadataservers)?

**Comment by iwanbk** [comment]
> @iwanbk I suppose we would store this in the same etcd as used for 0-stor and configured in https://github.com/zero-os/0-Disk/blob/master/docs/config.md#zerostorclusterconfig (metadataservers)?

Yep, so i think the nbdserver configs need to be updated?

> Thinking about this, this does make it obsolete to store it also from the nbdserver, as the tlogserver will have already stored the last sequence value there, no?

No.
Tlogserver only know it's last flushed sequence. It has no idea about last nbdserver flushed sequence

**Comment by GlenDC** [comment]
Why would the nbdserver configs have to be updated? Why not just use the same etcd cluster? This is only a feature needed in case the tlog config is defined for a vdisk anyhow... I don't see why we would need to require yet another etcd cluster config?

**Comment by iwanbk** [comment]
i'm not saying that we need another etcd cluster.

i only asked if the nbdserver configs (struct)  need to be updated, maybe add a field which point to the metadata server it needs to use.
Because i guess nbdserver config struct is currently doesn't have any zerostor related field.

**Comment by GlenDC** [comment]
We could, but I would really rather just store this in the ARDB, it would keep it all a lot simpler, and we already have a metadata (ARDB) server configured anyhow...

**Comment by iwanbk** [comment]
@GlenDC 

It seems to be simple, but i'm not sure which place to add the code for this?

Would be great if you can do it.

I could also do it if you give some clue about where to add the functionality.
Is it the LBA?

**Comment by GlenDC** [comment]
Ok I'll do it for you quickly today. Not a problem. It wouldn't be in the LBA no, as that has no place there. I'll open a PR for it and assign it for review for you so you can see how I did it and also confirm that it does what you want to do.
