### ISSUE TITLE
copy any needed tlog-related (meta)data during copy vdisk

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#280]
depends on:

+ #273;
+ functionality to copy (see: fork) tlogserver-dictated (meta)data;

**Comment by GlenDC** [comment]
@iwanbk how would we copy metadata and whatever else from a given vdisk onto a new vdisk, now that we use 0-stor?

**Comment by iwanbk** [comment]
We can't fork the metadata anymore using 0-stor because the metadata is double linked list now.

For the aggregation, 0-stor provide a kind of reference counting, so i think we don't need to copy the aggregation

**Comment by GlenDC** [comment]
I don't see what a double link list has to do anything with the fact that you can't fork anymore, please give more details.

So if we can't fork, what is the plan then in relation to the 0-stor metadata and whatever else is needed to be copied for the tlog stuff of a vdisk.

**Comment by iwanbk** [comment]
> I don't see what a double link list has to do anything with the fact that you can't fork anymore, please give more details.

unlike the old aggregation which only has `prev` pointer, double linked list also has `next` pointer which can only point to one destination

> So if we can't fork, what is the plan then in relation to the 0-stor metadata and whatever else is needed to be copied for the tlog stuff of a vdisk.

We copy the metadata

**Comment by iwanbk** [comment]
> We copy the metadata

Oh, just realized the problem if we copy it to same etcd server.
Need a way to fork it then in this case

**Comment by GlenDC** [comment]
Why is that an issue for copying? is this metadata not linked to to a unique ID, which for our use case could be the vdiskID? And I thought all vdiskIDs were guaranteed to be unique?

**Comment by iwanbk** [comment]
> Why is that an issue for copying?

Was mixed it with something, sorry. Related to the things in yesterday discussion on 0-stor channel about dedup.

> is this metadata not linked to to a unique ID, which for our use case could be the vdiskID? And I thought all vdiskIDs were guaranteed to be unique?

Yep. It is unique.

It currently rely on the fact that aggregation has `vdiskID` field. and metadata key is hash of the aggregation.

But i'm afraid that it might cause if for some reason, we remove that field.
what do you think?

**Comment by GlenDC** [comment]
@iwanbk it shouldn't cause any issue to remove the vdiskID field in the aggregation as it shouldn't even be there. Look at for example deduped storage. The blocks itself on the ARDB data servers have no clue to which vdisk or how many vdisks they belong, and that's how its supposed to be. Its the metadata that links everything together, which is already how it works for vdisk backups, and deduped vdisks.

**Comment by GlenDC** [comment]
There are 3 possible scenarios when copying a vdisk type which has tlog support:

1. both the source- and target vdisk have a tlogcluster configured, in which case we can either fork the tog chain (see: copying the reference metadata) if the tlogclusters are the same for both vdisks, or copy the entire tlogdata in case the clusters are different;
2. only the target vdisk has a tlogcluster configured, in which case we need to generate the tlogdata from scratch (perhaps using the new generator written for PR #453?) as part of the copy process;
3. only the source vdisk has a tlogcluster configured, in which case nothing tlogcluster related has to be done;
