### ISSUE TITLE
deleted any existing tlog-related (meta)data during delete vdisks

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#281]
depends on:

+ #273;
+ functionality to delete tlogserver-dictated (meta)data;

open questions:

+ Should we also delete all aggregations? 
  + And what to do if the aggregations are used by multiple chains (see: forks)?

**Comment by GlenDC** [comment]
@iwanbk how would we delete metadata and whatever else for a given vdisk, now that we use 0-stor? And what about the aggregations? I suppose we keep them there?

Or should this be deleted using a different zeroctl `delete` command rather than combining it with the already existing `zeroctl delete vdisk` command?

**Comment by iwanbk** [comment]
> @iwanbk how would we delete metadata and whatever else for a given vdisk, now that we use 0-stor? And what about the aggregations? I suppose we keep them there?

We can simply delete the metadata because we can't forked it.
For the aggregation: keep if there is still another vdisk referencing it, otherwise delete it

Do we need this in alpha-8 milestone, because deleting 0-stor object is planned in beta-1 milestone

**Comment by GlenDC** [comment]
It's not in the milestone plans on zero-os/home, so I guess not. I'll move this issue to beta-1.

What about issue #280, is everything we need for that issue already available in 0-stor, or should it also be moved to beta-1?

**Comment by iwanbk** [comment]
> What about issue #280, is everything we need for that issue already available in 0-stor, or should it also be moved to beta-1?

Please move it also

**Comment by iwanbk** [comment]
things to do:
- remove metadata
- remove reference list to the aggregation stored in 0-stor, and remove the aggregation if there is no other reference
