### ISSUE TITLE
Create boot disk template

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-Disk#297]
Basically needs to be done, by taking the blocks in the boot disk data volume (data volume in which nbdserver writes changes to the bootdisk) and combining it in the deduped storage of the bootdisk back into one volume again. Once the merged volume as been created, we can export it and later on import is again as a new template.

Requirements:
- add a command that will create this merged volume.

Depend on how https://github.com/zero-os/0-Disk/issues/298 is implemented

**Comment by despiegk** [comment]
no longer needed because we should use export/import for this
