### ISSUE TITLE
Space-Optimized Storage Type (deduped/nondeduped hybrid)

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#298]
At the time of writing the `boot` vdisk type is a pure `deduped` storage. This is great and intended as it means we can dedupe all blocks, of which a lot exist for an OS image. However it has the unintended effect that the after-install (user-specific) data is also being deduped, while this content is most likely unique and used by that user only. Microsoft's Windows is an extreme example of this, as it is constantly updating its registers. And while these registers are on a relatively few amount of shards, it produces a lot of different block content versions, and thus spamming the deduped storage full of data.

Because of this, a new hybrid storage is proposed, which would be a combination of a deduped and nondeduped storage.

The image (and thus template) data would still (possibly) be read and stored into a deduped storage. But all write-like operations triggered by the user (nbdserver) would write to a nondeduped storage.

This would result in the following operation flow:

```go
// NOTES:
//   + The nondeduped storage would be created without template support;
//   + The deduped storage would be created with template support;
//   + Both the deduped and nondeduped storage would write to the same data storage servers;
type bootStorage struct

// nondedupedStorage.Set
(bs *bootStorage) Set(...) (...)

// bs.Get -> Merge Content -> bs.Set
(bs *bootStorage) Merge(...) (...)

// nondedupedStorage.Get -> OK
//    |
//    --> FAIL --> dedupedStorage.Get
(bs *bootStorage) Get(...) (...)

// nondedupedStorage.Delete && dedupedStorage.Delete
(bs *bootStorage) Delete(...) (...)

// nondedupedStorage.Flush && dedupedStorage.Flush
(bs *bootStorage) Flush(...) (...)

// nondedupedStorage.Close && dedupedStorage.Close
(bs *bootStorage) Close(...) (...)

// nondedupedStorage.GoBackground && dedupedStorage.GoBackground
(bs *bootStorage) GoBackground(...) (...)
```

**Comment by GlenDC** [comment]
Planned for milestone 8 (https://github.com/zero-os/home/blob/649a91d887d7081c42f47cf38f993d12b666427b/milestones/1.1.0-alpha-8.md) at the time of writing. Can be picked up in milestone 7 already if time allows us to.

**Comment by GlenDC** [comment]
I propose that when a `boot` vdisk:

+ defines NO `rootStorageCluster` (root == template), we simply run it as a deduped storage. This makes sense as the hybrid version described above relies on a rootStorageCluster, and this would mean we can still create template boot vdisks;
+ defines A `rootStorageCluster` (root == template), we run the vdisk using the hybrid boot storage described above;

I think this added proposal makes it all click together.

**Comment by GlenDC** [comment]
A PR (#312) has been opened to resolve this issue.

If we assume that most data will still be deduped (as in template data, which consists of the installed OS and built-in applications), we might have a slower performing vdisk, because of the priority given to the nondeduped internal storage, vs the deduped internal storage, where such data would be (if already local ofcourse). The slow down would come from the fact that there would first be a communication with the nondeduped ardb, to only than realize that the data is actually deduped (if we assume the data in question exists at all). So there is some wasted network traffic. And thus if most data would be deduped, we would get this waste for most of our request, and thus have an extra delay. How much that would effect us, is mostly dependent upon network speed.

We should perhaps get some extra profiling numbers to know how much this impacts us, but just thinking about this problem, I do not immediately know about how to resolve it.

1. Having some kind of cache, which would define whether a value is deduped or not, could help, but might not be realistic. Because again, most data would be deduped, and we talk about a big image such as Windows, it would be very impractical to keep an inmemory cache for that. Caching whether or not data is nondeduped is more practical but not useful. Because if for a given index we do not know it is nondeduped or not, we still have to check the nondeduped storage first, because an index might both exist in deduped (older) and nondeduped (newer) storage;
2. If we would know for sure that the metadata and data for EVERY given index would be stored on the SAME storage server, and they would use the same storage engine (eg redis), we could pipeline each request as a smart request (eg in the form of a lua snippet), which would allow us to fetch the data, in  a single request (whether it exists in nondeduped, deduped or both). This would be the most naive and easy solution I can think of, but right now this is not possible, as all three types of data (dedup metadata, dedup data and nondedup data) are stored on different storage servers. In milestone 7 we're moving away from the metadata storage server, but as we might start using 0-stor to store metadata, it might make such a solution even more implausible;

I'll profile the boot vdisk with this new storage, vs the pure nondeduped storage, and attach that research to the open PR(#312). But I think we can say with a fair amount of certainty, that the current proposed solution will probably be a trade-off in speed vs space, where we gained a big win in space, but sacrificed speed. As hard-disk space is cheaper and cheaper every day, I'm not sure this is the right trade-off  to make. But then again, we might be able to win in both areas if only we adapt our solution or move into a new direction altogether. This is to be found out, but perhaps not in this milestone. Depended on the profiling results, the currently proposed solution (see PR #312), might be sufficient, and if so, we could worry about this trade-off later

**Comment by despiegk** [comment]
think there is some misunderstanding here, the metadata of dedupe should never be in 0-stor !
also if we get the blocksize back to 4kbyte again we can potentially stay wit dedupe, we need to implement the scrubbing though, this will become more urgent.

the right way how to know to which DB to go is by means of a bitmap, 1 MB bitmap can address 32 GB of data when 4 KB blocksize. This bitmap would tell you if the data is in the overlay (location based) storage space, if not then the dedupe path applies. This would completely resolve your performance issue.

**Comment by GlenDC** [comment]
> the right way how to know to which DB to go is by means of a bitmap, 1 MB bitmap can address 32 GB of data when 4 KB blocksize. This bitmap would tell you if the data is in the overlay (location based) storage space, if not then the dedupe path applies.

Clever, yeah that might indeed resolve _the_ performance issue I had in mind. And 1 MB does seem small enough that we can also keep it in the service memory while a vdisk is loaded. So yeah that could work, and I guess we can store it in the metadata when the vdisk is being flushed.

**Comment by GlenDC** [comment]
As discussed. For now the boot storage will remain deduped. This semideduped storage will be pushed to master as it is, but will not be used for now by any vdisk type. As we'll fee focus on the import/export feature first (see #317).
