### ISSUE TITLE
Add For-Orchestrator-Failure (stderr) logger

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#300]
Part of the self-healing as described in https://github.com/zero-os/0-orchestrator/blob/master/specs/selfhealing/storage.md

In certain scenarios the nbdserver has to communicate with the 0-orchestrator:

+ a tlog server crashed;
+ a storage server crashed, rebalancing of data is required;

In these cases it will do so by using a special logger, which will log the failure/success messages via stderr, which will then be picked up by the 0-watchdog and delegated over to the 0-orchestrator.

The proposed format by @FastGeert is:

```
FAILURE: {"type": "storageengine-failure", "data": "10.100.0.1:22005"}
```

and

```
SUCCESS: {"type": "storageengine-rebalance", "data": "10.100.0.1:22005"}
```

The proposed format might not be final, but it should at the very least serve as a starting point.

---

Note: as this feature is going to be used by all 0-services, we might want to move this into a more common repo, perhaps even 0-orchestrator, but for now we could simply have it as a new root module in the 0-Disk repo.

**Comment by zaibon** [comment]
>  we might want to move this into a more common repo

I like the idea that we could have a module re-usable in mutliple 0-services, but
how would you see this module ? Since it uses a special logger to output on stderr, the implementation depend on the logger used in the 0-service.
Would that module just expose an interface then ?

**Comment by GlenDC** [comment]
I don't think it depends on the logger at all, I mean this doesn't have anything to do with the normal logging AFAIK.

It would just be printing to stderr, via something as simple as `fmt.Fprint(f/ln)`. I don't think this needs to be hooked up to the normal logging. Or what was your reason for thinking it should @zaibon?

**Comment by zaibon** [comment]
No reason whatsoever and you are right a simple write to stderr is sufficient

**Comment by iwanbk** [comment]
This is needed by https://github.com/zero-os/0-Disk/pull/337#discussion_r128181872

**Comment by GlenDC** [comment]
Cool, this can be worked on in milestone 7 then. I already created a repo for it: https://github.com/zero-os/0-log

**Comment by GlenDC** [comment]
@chrisvdg once the 0-Log library is implemented:

+ Import the library into 0-Disk;
+ Integrate the library into the 0-Disk log module:
  + provide a small api to easily notify the 0-Orchestrator failures using JSON messages;

**Comment by GlenDC** [comment]
Here is a potential (partial) API:

```go
type StorageClusterFailure struct {
    ClusterID string
    Server StorageServer
    VdiskID string
}

// class of notification message
// NOTE: not sure if state is a good name
type MessageState uint8 // marshal to json as string version
const (
   StateSuccess MessageState = iota
   StateFailure
)

// type of notification message
// NOTE: not sure if type is a good name
type MessageType uint8 // marshal to json as string version
const (
   MessageStorage MessageType = iota
)

// Message is the format we'll marshal to JSON
// and send over 0-Core to 0-Orchestrator
type Message struct {
   State MessageState   // e.g. StateSuccess
   Name MessageType     // e.g. MessageStorage
   Data interface{}     // e.g. StorageClusterFailure
}

// Log JSON message over stderr on 0-core, using 0-log,
// targeted at 0-Orchestrator.
func Notify(MessageState, MessageType, interface{})
```
