### ISSUE TITLE
Add Slave Storage Cluster support to 0-Disk

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#302]
The slave storage cluster is used as a backup for the primary storage cluster. It is to be kept in sync with the primary storage cluster by the tlog server.

In case of a (partial) failure in the primary storage data, the nbdserver will fetch the lost data from the slave storage cluster as part of the rebalancing of data onto the primary storage servers that do still function. In case a failure happens in the slave storage server, the same flow will happen, but reversed.

This issue requires #301 (and any other rebalancing FRs) to be fully defined, if not already resolved.

**Comment by zaibon** [comment]
I think we are mixing two issues here.
- Backup storage support using tlog: This doesn't requires the rebalancing flow to be implemented.
- The failure scenrario and usage of the backend storage as fail over.

**Comment by iwanbk** [comment]
`Backup` here is the same as `Slave`, right?

> In case of a (partial) failure in the primary storage data, the nbdserver will fetch the lost data from the backup storage cluster as part of the rebalancing of data onto the primary storage servers that do still function

nbdserver with tlog already moved to slave, but without rebalancing.

**Comment by GlenDC** [comment]
We got to start agreeing on terminology, because using different words gives misunderstandings like this. We also use 3 different words for the template server: template, root and fallback. And who knows where else we use multiple words for the same concept.

**Comment by GlenDC** [comment]
@zaibon we need to have a meeting about this on Monday, as I have some questions with this, and also its relationship with #357.

**Comment by GlenDC** [comment]
duplicate of #357 and all the other (more specific) slave (self-healing) issues.
