### ISSUE TITLE
tlogserver: support backup storage

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#303]
A vdisk can optionally define a backup storage cluster in the 0-Disk config. This backup storage cluster is to be kept in sync with the primary storage cluster, by the tlogserver.

TODO:

+ define and describe how this would be integrated into the tlogserver;

**Comment by iwanbk** [comment]
If backup == slave, tlog server already supported it.
We might still need to improve the configs though.

**Comment by iwanbk** [comment]
Still need this?

**Comment by GlenDC** [comment]
Nope. Backup is something different, and the term was confused with slave, due to us using the same terms for the same thing.
