### ISSUE TITLE
spread metadata of deduped storage

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#304]
Currently the deduped storage is storing its metadata on a single storage server (defined as the `metadataStorage` cluster). This makes the metadata a critical point of failure, as the metadata contains the mapping between hashes and block indices, it would mean that the entire vdisk would effectively be deleted once its metadata storage is unavailable.

Therefore it is proposed to forget about the MetadataStorage as a concept altogether, and spread the metadata in a similar fashion as the data is already spread. It would basically make the meta data storage as done in the LBA code very similar to how it is done in the nondeduped storage code.

The simplest solution would simply be turning LBA's `MetaRedisProvider` interface into:

```go
// RedisProvider is used by the LBA,
// to retreive a Redis Connection
type RedisProvider interface {
	RedisConnection() (redis.Conn, error)
}
```

and use that one within the LBA struct, rather than the previously defined `MetaRedisProvider`. The ardb code which creates the LBA Object will already do the correct thing, as the used provider already provides that function, effectively spreading the data using the simple `index-modulo` algorithm.

With this change the `MetaRedisConnection` method of `ardb.redisProvider` can also be deleted, as wel as any other meta-related content within that struct (e.g.: the `metaConnectionConfig` property).

NOTE that the zeroctl copy and delete commands will also have to be adapted together with this change (e.g.: functions such as `copyDedupedVdisk` will have to be adapted to work with the multiple data storage servers, instead of a single metadata storage server).

This feature also means that the `validateMetadataStorage` check in the config module is now obsolete, and should be deleted and validation code that uses it should be adapted accordingly.

Last but not least, unit test code should be adapted where (and only where) required.

**Comment by despiegk** [comment]
- how would this provide redundancy? because also today for data of non deduped volumes there is no redundancy?
- would metadata data of LBA's still be grouped? (is it grouped in the first place, with that I means do we store metadata per groups of e.g. 256 LBA blocks, if it is grouped what is group size?)

**Comment by GlenDC** [comment]
> how would this provide redundancy? because also today for data of non deduped volumes there is no redundancy?

There is also no redundancy directly in the ardb code for deduped code either. In fact as deduped data is shared between multiple disks, a failure is even more damaging.

The redundancy (for those vdisk types which support that: `VdiskTypeBoot` and `VdiskTypeDB`) is provided by:

+ Backup Storage Server, kept in sync by the Tlog Server (planned for milestone 7);
+ The Tlog Server, which stores all transactions logs using erasure coding and replications (already implemented);

> would metadata data of LBA's still be grouped?

Yes it is grouped, they are stored per `128` entries. Docs about it can be found here https://github.com/zero-os/0-Disk/blob/master/docs/nbd/lbalookups.md. And yes they'll remain grouped.

It's good you bring this up though. This will impact how the LBA data will be spread, as a simple index module operator wouldn't really work indeed, if we want to keep them grouped, which I think we should. Details of this will have to be worked out as part of this issue. But I think that would have become clear as an issue anyhow, once work on this issue started.

**Comment by GlenDC** [comment]
This idea is now superseded by a new proposal, which can be found as issue #474.
