### ISSUE TITLE
spread metadata of tlogserver's slave syncer

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#305]
Currently the tlogserver is storing the last synced sequence in the metadata server. This is very error prone, and would make this effectively a critical point of failure. Better would be if we store this metadata on all data storage servers, similarly to how the rest of the tlog code already does it. This way the data would be stored on multiple servers.

At startup we would than somehow need to come to a consensus on which metadata to use, in case different data servers have different versions available for the relevant metadata.

**Comment by despiegk** [comment]
- aren't there already lots of dataservers? and would this not make the tlog server slow

**Comment by GlenDC** [comment]
> aren't there already lots of dataservers?

The same data servers would be used.

> and would this not make the tlog server slow

Depends on how it is implemented, I wouldn't think it would make it slower, even though it already is slow as it is.

We already do this to store the last processed sequence on the server side. So it's not a new idea. We could play it smarter by not having to replicate to all K+M servers for the metadata, as we are not using erasure coding for it anyhow.

This can be further thought out as part of this issue. And comparative benchmarks can be made, to ensure no performance decay.

**Comment by iwanbk** [comment]
It wont make it slow because the slave syncer work in async way

**Comment by iwanbk** [comment]
Changed the title to make it clear that it is about nbdserver slave syncer's metadata, not the main tlogserver.

**Comment by despiegk** [comment]
believe wrong implementation, see other issue to do with using zero-stor lib which should resolve this.

**Comment by GlenDC** [comment]
Closed in favor of the approach discussed in issue #311.
