### ISSUE TITLE
remove metadata storage cluster from 0-Disk

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#306]
This feature is about removing the concept of a separate metadata server:

+ this would make the code simpeler;
+ it would keep the metadata close to the data it is linked to (as in on the same server);
+ it would make it actually possible to also have self-healing being applied to the metada, as currently in the slave-primary self-healing plans there is no design for the metadata server, meaning that we would simply have a non-working vdisk forever if the metadata server would stop crashing;
+ it would keep all storage servers (also called engines) well balanced in terms of data load (because right now  the metadata server is probably much lighter in terms of data compared to the data servers);

Here is what it would mean for the metadata already stored:

+ The deduped LBA data we could spread over the data servers, using the sector indices, in a similar way as we use block indices for non-deduped vdisks to define which server to store to;
   + ~However there is in my opinion a much better proposal which would spread the deduped LBA data in a more direct mapping and which get rid of the concept of the LBA completely. You can find this proposal under #474;~
+ The tlog-enabled storage metadata (lastFlushedSequence) would simply be stored on the first available data server (meaning the first one in the array of specified data servers which has non-rip status);

**Comment by zaibon** [comment]
I think this make sense. Was there any special reason we used a single metadata ardb in the first design ?

**Comment by GlenDC** [comment]
I am not sure. The concept of a metadata ardb was already there in the design when I came on board. @robvanmieghem might know more about this, as I think he was the designer behind it.

**Comment by robvanmieghem** [comment]
In general I agree that if we can eliminate the dedicated metadataserver, this is a good thing and it looks good to me
Originally, the tlogserver was filling the slaves, is this still the case ?, if not, it does , again, put extra delay on the nbdserver and make sure the slave recovery/failover is documented.

**Comment by GlenDC** [comment]
> Originally, the tlogserver was filling the slaves, is this still the case ?

Yes this is still the case. In a normal scenario where a tlog and slave is configured for a vdisk, the tlog will be filling up the slave.

Only if a primary server falls out, that specific server will now be read/written directory from/to the mapped slave server, while the 0-Orchestrator figures out what to do with this now `offline` primary server. That means that during that time the tlog cluster will not write data to _that_ specific slave server, until an action has been taken by 0-Orchestrator to fix the primary server or to take action as the server might be dead for good.

**Comment by GlenDC** [comment]
Changed this from a proposal into a feature request, as everyone seems to agree.
