### ISSUE TITLE
support hot reloading in tlogclient

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#313]
The tlogclient has an array of tlog rpc addresses, and always aims to establish a connection with the first address in list (if not already). When this connection fails, all addresses module shift to the left, such that the next address becomes the first one and thus used to establish a connection (if possible at all).

Currently these addresses are static once defined during the creation of the Tlog Client. Meaning that if the yaml config were to be updated with new tlog rpc addresses, the tlogclient wouldn't update them (upon SIGHUP signal receival).

It is probably required that the tlog client always has the latest tlog rpc addresses available and used, and thus it should have Hot Reloading support (which is done using a SIGHUP signal as with all the rest of the 0-Disk codebase).

I would assume that in case we are reloading the config (because we received a SIGHUP signal), and the first address is different, that we need to establish a new connection. The question is however, whether or not it should take into account the shifting, and only establish a new connection if even when shifted the new connections are still different compared to the ones stored.

**Comment by despiegk** [comment]
i think we need to rework how we do our config management, having all in config files is not at all the right approach. Something like etcd is better solution also etcd allows to check when there are changes in a unified way and then reload.
see #316

**Comment by despiegk** [comment]
suggest to close this FR and move all to #316 which will resolve this

**Comment by zaibon** [comment]
I'll see what #316 is about and decide what to do with this one.

**Comment by GlenDC** [comment]
I don't think #316 will close this issue, as the main issue is that tlogclient shouldn't hardcode the tlog rpc addresses, no matter if the config comes from a hot-reloaded file or from etcd.

**Comment by iwanbk** [comment]
>  as the main issue is that tlogclient shouldn't hardcode the tlog rpc addresses,

It was immutable, but not anymore :)

The client has `ChangeServerAddrs` method to change the tlog server addresses.

And i think it is the user responsibility to call this functions.

**Comment by GlenDC** [comment]
> And i think it is the user responsibility to call this function

Sure I agree with that, as the tlogclient is supposed to be generic.
