### ISSUE TITLE
multiple tlog : logs might be stored twice on failover

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#314]
scenario:
- client use tlogserver 1 (ts1)
- client send sequence X
- ts1 successfully stored sequence X
- ts1 crashed -> client got no response about sequence X successfully stored
- client move to tlogserver 2(ts2)
- client resend sequence X
- ts2 store sequence X again

**Comment by despiegk** [comment]
this is a very remote chance and if this happens which is timing wise almost impossible there would be some data leakage which is ok.

**Comment by GlenDC** [comment]
> this is a very remote chance

I'm sure you know, but once we get beyond a certain threshold of users, remote chances become pretty common place.

---

@iwanbk would these double-stored transactions in this scenario always be consecutive? If so, it shouldn't be an issue ever (in case of rollback/replay), as applying a transaction consecutively twice shouldn't ever been an issue AFAIK.

**Comment by iwanbk** [comment]
> would these double-stored transactions in this scenario always be consecutive

yep
 

> as applying a transaction consecutively twice shouldn't ever been an issue AFAIK.

Yes, it is true for single transaction.

please note that an aggregation consists of multiple transactions. 
Multiple transactions seems to be not an issue as well, but not really sure about this.
