### ISSUE TITLE
tlogserver : remove hot reload support

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#315]
Because we have multiple tlog servers support, we should remove tlog server hot reloading support If we don't really have requirement for this feature

Reasons:
- we can simply change the config by killing current tlog server
- hot reload need careful race condition tests. e.g. : hot reload might happen during storing erasure encoded data: 1st piece might still use old config while other pieces use the new one
- less code to maintain

**Comment by despiegk** [comment]
see #316 
this is the proper way, killing is rather drastic

**Comment by despiegk** [comment]
suggest to close this one

**Comment by zaibon** [comment]
killing it is indeed not the right approach.
I'll see what #316 is about and decide what to do with this one.

**Comment by zaibon** [comment]
this becomes irrelevant with the introduction of etcd
