### ISSUE TITLE
exit nbdserver gracefully upon SIGTERM

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#323]
As reported in #288, the Cairo team seems to send a `SIGTERM` signal to the `nbdserver`, when done with it. Once the `tlogserver` and `nbdserver` processes have both exited, the VM is shut down. The `SIGTERM` signal is sent right after being done with the Vdisk.

We have to handle the `SIGTERM`, such that we can gracefully exit the nbdserver and shutdown any active vdisks. This will probably result in some errors in case there were active processes, but at least now it will be done gracefully rather than abrupt if not handled properly.

**Comment by iwanbk** [comment]
Suggest to wait until we have clear problem on #288, especially regarding the data left in OS cache and flush

**Comment by iwanbk** [comment]
I propose to do these things:
- reject any new connection
- close existing connection
- flush all received transaction

To solve #288, we only need to do the last thing, so we need to do that first.

**Comment by iwanbk** [comment]
> flush all received transaction

My proposed solution:
- add SIGTERM handler on main (nbdserver/main.go), it executes context cancellation upon SIGTERM. 
- upon context cancellation, vdisk wait for flush to be finished or exit with error if timeout reached
- after all vdisk exited/stopped, main exit -> not sure whether current main able to monitor vdisks lifetime

**Comment by iwanbk** [comment]
A work in progres can be found on `nbd-sigterm-handle` branch.
Big things left to implement:
- unit test
- gather error from vdisk flush, if any
