### ISSUE TITLE
update github.com/templexxx/reedsolomon to latest

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#332]
I try to keep packages up to date, and update them all bi-weekly.

`github.com/templexxx/reedsolomon` seems to have gotten some big updates, which would really help a lot with performance, but I don't have enough knowledge about that side of the codebase to confidently pull in those breaking changes, and fix them correctly.

Could you please update that package to latest, vendor it, and adapt our code?

**Comment by iwanbk** [comment]
already done on 0-stor-lib
