### ISSUE TITLE
Read performance of db disk type need improvement

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-Disk#336]
Created a vm on be-g8-3. Storage setup only had a primary storage cluster, no backup and no tlog.

Its write performance is very good (up to 80MB/s or > 18k iops)
```
root@geert:~# dd if=/dev/zero of=/dev/vdb count=5000 bs=1MB
5000+0 records in
5000+0 records out
5000000000 bytes (5.0 GB, 4.7 GiB) copied, 62.9515 s, 79.4 MB/s
```

The read performance is not adequate though. Only 3.x MB/s.
```
root@geert:~# dd if=/dev/vdb of=/dev/null count=100 bs=1MB
100+0 records in
100+0 records out
100000000 bytes (100 MB, 95 MiB) copied, 32.1374 s, 3.1 MB/s
```

**Comment by GlenDC** [comment]
Odd that writing (essentially redis' `HSET`) is so much faster than reading (essentially redis' `HGET`). The design of the nondeduped is really simple, basically just a controller for the ardb storage. I guess if you're reading often the same blocks we would be able to make that much faster by introducing some kind of cache, not sure if that's the right answer here. Will need some investigation when being worked on I guess, including some go profiling to see where the work currently is for this one, might give us a clue at least.

**Comment by GlenDC** [comment]
Any progress with this issue @chrisvdg?

**Comment by chrisvdg** [comment]
@GlenDC , no I've been looking into the pprof tool and trying to get the nbd server going, but it doesn't feel like cooperating on my machine

**Comment by chrisvdg** [comment]
Got it running locally and I don't seem to have this issue

Writing
`
root@eden:~# dd if=/dev/zero of=/dev/nbd1 count=5000 bs=1MB
5000+0 records in
5000+0 records out
5000000000 bytes (5,0 GB, 4,7 GiB) copied, 64,5018 s, 77,5 MB/s
`

Reading with Geert's setting (seems awfully fast)
`
root@eden:~# dd if=/dev/nbd1 of=/dev/null count=100 bs=1MB
100+0 records in
100+0 records out
100000000 bytes (100 MB, 95 MiB) copied, 0,016597 s, 6,0 GB/s
`

Reading with a higher count
`
root@eden:~# dd if=/dev/nbd1 of=/dev/null count=5000 bs=1MB
5000+0 records in
5000+0 records out
5000000000 bytes (5,0 GB, 4,7 GiB) copied, 33,5383 s, 149 MB/s
`

**Comment by iwanbk** [comment]
```
Reading with Geert's setting (seems awfully fast)

root@eden:~# dd if=/dev/nbd1 of=/dev/null count=100 bs=1MB
100+0 records in
100+0 records out
100000000 bytes (100 MB, 95 MiB) copied, 0,016597 s, 6,0 GB/s
```

Too fast, compared with next result

**Comment by chrisvdg** [comment]
Results when using Redis (previous results were from embedded Ledis using the -memorystorage flag)

Writing
```
root@eden:~# dd if=/dev/zero of=/dev/nbd1 count=5000 bs=1MB
5000+0 records in
5000+0 records out
5000000000 bytes (5,0 GB, 4,7 GiB) copied, 26,6692 s, 187 MB/s
```
Reading with count 100
```
root@eden:~# dd if=/dev/nbd1 of=/dev/null count=100 bs=1MB
100+0 records in
100+0 records out
100000000 bytes (100 MB, 95 MiB) copied, 0,636331 s, 157 MB/s
```
Reading with a higher count
```
root@eden:~# dd if=/dev/nbd1 of=/dev/null count=5000 bs=1MB
5000+0 records in
5000+0 records out
5000000000 bytes (5,0 GB, 4,7 GiB) copied, 31,9511 s, 156 MB/s
```

**Comment by GlenDC** [comment]
Does seems suspiciously fast indeed.

Try testing with a remote ARDB server. Checkout my comment https://github.com/zero-os/0-Disk/issues/358#issuecomment-321723465 out.

Also never profile with the inmemory storage. Like seriously, never do that.

**Comment by chrisvdg** [comment]
The 6GB/s is because it wasn't the first time I ran it, when I rerun with Redis I also get around 6GB/s

**Comment by GlenDC** [comment]
By the way if you're going to write zeroes only (like @FastGeert does), we do have a very special scenario that is like never going to happen in production. Because you have to know that we don't write pure-zeroes blocks to the ARDB. In fact we delete it if it existed before that. So if you only ever write blocks, we'll never be sending blocks to the ARDB.

Not sure why that would make reading so slow though, as it should just not find anything and give back nil. But for some reason in Geert's test it does make it slower.

What do your benchmarks say so far @chrisvdg?

**Comment by chrisvdg** [comment]
as in the profiles?

**Comment by GlenDC** [comment]
Yes, and also your thoughts on it.........

**Comment by chrisvdg** [comment]
CPU profiling:

reading
[profile30sReadNBD2.pdf](https://github.com/zero-os/0-Disk/files/1217990/profile30sReadNBD2.pdf)
writing (while running the large count)
[profile30sWriteNBD2.pdf](https://github.com/zero-os/0-Disk/files/1217991/profile30sWriteNBD2.pdf)

For Writing a lot of time is spend at isZeroContent, but ofc this is when zero content was written to it
Other then that nothing really jumps out
For reading, I'm not sure if github.com/zero-os/0-Disk/nbd/ardb/storage.(*nonDedupedStorage).getPrimaryContent still good at 240ms?
The function is just doing a redis query right?

**Comment by GlenDC** [comment]
> (*nonDedupedStorage).getPrimaryContent still good at 240ms?
> The function is just doing a redis query right?

"Just doing a redis query" does also include sending, waiting and receiving the reply from the server. If you test with a remote server, you'll see that delay going up, and change depending on your connection speed.

**Comment by GlenDC** [comment]
I didn't check the attached pdfs before. I see what you mean. You do have to know that this is not the average time of one call AFAIK, but rather the accumulation of all calls during your profile snapshot.

**Comment by FastGeert** [comment]
Tried to reproduce, and the problem seems to be vanished both reading and writing go at approx 90MB/s

```
dd of=/mnt/ramdisk/garbage2.dat if=/mnt/realdisk/garbage2.dat bs=4k
2621440+0 records in
2621440+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 119.757 s, 89.7 MB/s
```

90MB/s is acceptable for now
