### ISSUE TITLE
broken tlog/tlogserver/server test

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-Disk#349]
make testcgo fails from time to time locally(adds-etcdconfig and master branch) and on Travis (adds-etcdconfig branch so far?) for github.com/zero-os/0-Disk/tlog/tlogserver/server

output is a bit lengthy so linking the raw output file: https://pastebin.com/GiaJ8zfw

the test errors out with (line 1007):
`panic: test timed out after 5m0s`

**Comment by iwanbk** [comment]
duplicate of #275
