### ISSUE TITLE
redo switch-to-slave-cluster feature using the stderr logger

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#357]
Originally the `switch-to-slave-cluster` was implemented as follows:

1. read the config yaml file (which used to be the way to store configs, and it contained _all_ configurations) ;
2. use the slave cluster as the primary cluster for a given vdisk;
3. delete the slave cluster for the vdisk;

However, since #330 it has been decided (in agreement with @FastGeert) to only ever read from the config source (etcd), at least within the 0-Disk codebase. It's only the upper layers which write the config. Instead we should notify the upper layers using the stderr layers as described in issue #300, as 0-Disk doesn't have enough knowledge to properly do the switching of clusters.

In milestone 6 the original feature as described above has been disabled.

Once issue #300 is resolved, this feature can be re-implemented and enabled.

**Comment by GlenDC** [comment]
Rather than switching to the entire cluster, I think we can simply switch the server that requires switching, and apply a technique as follows:

1) Read/Write from/to a primary server of a certain index;
2) Get an error -> Retry;
3) retry fails as well, mark that index (that is to say the index before the modulo operation was applied) as invalid, which would now make it use the slave cluster provider (if available);
4) while we mark that index as invalid, we also report to the 0-Orchestrator, using 0-log, that server X of cluster Y for vdisk Z is unavailable;
5) when we receive an update in the redis provider (config update), all server indices are now defaulted back to primary storage usage (thus the ones that were previously using slave because of a critical are now using primary again, just like the server indices that never switched in the first place);

Note that this feature should work even if the slave cluster has an amount of servers not equal to the amount of servers available in the primary storage.

**Comment by GlenDC** [comment]
As a consequence of this design, we do have to deal with a potential race issue:

If both tlogserver and nbdserver are writing to the same slave cluster, we have a race condition. Even though the nbdserver is probably always the most up to date, and so a write coming from the nbdserver is more valuable, there is no way at the moment to guarantee this.

The simplest solution would be make the slave cluster read-only for the nbdserver, but than what to do with the data it wants to write?

Another solution would be to somehow have a mechanism in place that would help us prevent such a race condition. When working with databases this is often done using a counter or something similar, but I don't see that scaling for the amount of data we write to it...

So what to do?

**Comment by iwanbk** [comment]
> Rather than switching to the entire cluster, I think we can simply switch the server that requires switching,

I think it is better idea, but how about make it next step? So we can start small and improve it gradually.
Except that it is already needed now

> If both tlogserver and nbdserver are writing to the same slave cluster, we have a race condition. Even though the nbdserver is probably always the most up to date, and so a write coming from the nbdserver is more valuable, there is no way at the moment to guarantee this.
this already prevented partly

switching flow related to tlog server:
- nbd detect error in primary cluster 
- nbd ask tlogserver to finish the flush to slave
- tlog server flush to slave using tlog replay
- tlog server stop the slave sync mechanism -> slave sync already stopped, so no race condition :)
- tlog server restart the slave sync mechanism on SIGHUP or by etcd watch -> of course still race condition if it has same slave again, but it is orchestrator responsibility

**Comment by FastGeert** [comment]
> If both tlogserver and nbdserver are writing to the same slave cluster, we have a race condition. Even though the nbdserver is probably always the most up to date, and so a write coming from the nbdserver is more valuable, there is no way at the moment to guarantee this.

This is a none issue after the move to the 0-stor for t-log. On top of that, the tlogs will never be written to the same storage cluster as the actual blocks because tlogs will be written to hdd's while the blocks itself to ssd

**Comment by GlenDC** [comment]
Will be resolved by the specific issues:

+ Ensure config is valid (issue #442);
+ Ensure tlogserver and nbdserver don't use a slave storage server at the same time (issue #444);
+ Failover to the slave server when a primary server fails (issue #445);
+ Resilver slave data (back) into the primary server(s) (issue #445);
