### ISSUE TITLE
additional fields for tlog config

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#360]
These fields are needed for 0-stor integration
- itsyou.online organization (string)
- itsyou.online namespace (string)
- itsyou.online client ID (string)
- itsyou.online secret (string)
- 0-stor server addresses ([]string)
- Metadata server addresses([]string)

More info about organization & namespace can be found on https://github.com/zero-os/0-stor/blob/master/specs/concept.md#namespaces-concept

**Comment by GlenDC** [comment]
This issue is blocked and has to wait until PR #330 is finished and merged.

@iwanbk aren't you also missing the actual storage endpoints, or is that something 0-stor figures out based on that information only?

And I assume this information is replacing the TlogStorageCluster (ARDB) sub config?

**Comment by iwanbk** [comment]
> This issue is blocked and has to wait until PR #330 is finished and merged.

Do you have ETA for this?

> @iwanbk aren't you also missing the actual storage endpoints, or is that something 0-stor figures out based on that information only?

Ah yeah. Issue description updated

> And I assume this information is replacing the TlogStorageCluster (ARDB) sub config?

yeah, but can we keep this sub config until 0-stor integration fully finished.

**Comment by GlenDC** [comment]
> Do you have ETA for this?

Hopefully in about 6 hours, worst case tomorrow (23:00, 2/07, GMT+1).

> Metadata server addresses

Which metadata server addresses are this? ARDB? Or 0-Stor as well?

**Comment by iwanbk** [comment]
> Which metadata server addresses are this? ARDB? Or 0-Stor as well?

etcd

**Comment by GlenDC** [comment]
@chrisvdg these fields can be added to the `VdiskTlogConfig` struct. Make sure to validate these fields as is appropriate, and add the unit tests to help validate your implementation.

**Comment by chrisvdg** [comment]
@iwanbk , any specs for the validation?

**Comment by iwanbk** [comment]
>  any specs for the validation?

Non empty value is fine for now

**Comment by GlenDC** [comment]
> > any specs for the validation?

> 0-stor server addresses ([]string)
> Metadata server addresses([]string)

Besides the non-empty, also validate these server addresses using the `valid.IsDialString` method. It doesn't tell us if the servers are reachable, but at least it gives us some validation.

**Comment by GlenDC** [comment]
Fixed in ready-for-merging PR #365.
