### ISSUE TITLE
tlogserver: notify 0-Orchesrator when 0-Stor server is down

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#371]
In case a 0-stor server used by the tlogserver for a vdiskID is unavailable due to whatever critical error, we should notify the 0-Orchestrator about this, using the logger described in #300, so it can do something about it.

This issue is blocked until #300 is resolved.

**Comment by iwanbk** [comment]
@GlenDC @chrisvdg can you point me which API to use? i'm not sure which one

**Comment by chrisvdg** [comment]
@iwanbk log.Broadcast should be used
example:
https://github.com/zero-os/0-Disk/blob/master/config/source_etcd.go#L21

docs:
https://github.com/zero-os/0-Disk/blob/master/docs/log.md

**Comment by iwanbk** [comment]
About the https://github.com/zero-os/0-Disk/blob/master/docs/log.md#status-codes, do we have complete list of status codes elsewhere? Or we simply add status code as we need it?

I need `cluster failed` or `cluster unknown failed` to states that the server/cluster failed without clear reason.

**Comment by iwanbk** [comment]
Oh, i see that the codes is defined at https://github.com/zero-os/0-Disk/blob/master/log/broadcast.go#L79-L83.

But i wonder if 0-orch already standardized the status codes

**Comment by chrisvdg** [comment]
No we don't, these are codes we specified ourselves, so we add them as needed and communicate this to the 0-Orch team or whoever needs to handle this code
