### ISSUE TITLE
configs : example of tlogserver config

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#375]
Need simple example of tlogserver configuration file.
(perhaps like what nbdserver has in https://github.com/zero-os/0-Disk/blob/master/docs/config.md#reading-data-1)

While checking the docs, i also can't find the way to configure these:
- flush size
- flush time
- K (number of data shards)
- M (number of parity shards)
- private key and nonce for the encryption

also just realize that most of the above configs was not exist in the old config file, can only be configured from command line.

@GlenDC @chrisvdg feel free to self assign this issue as i'm not sure which one of you can be assigned to this  issue

**Comment by iwanbk** [comment]
the example was exist in old readme, might be just moved but i can't find it

**Comment by GlenDC** [comment]
None of that is possible using the configuration (at the moment).

Will that stuff still be required once we switch to 0-Stor?

**Comment by GlenDC** [comment]
If those variables would be per-vdisk, we could add them to https://github.com/zero-os/0-Disk/blob/master/docs/config.md#vdisktlogconfig as a new optional subconfig. Or is it more something specific per tlogcluster?

**Comment by iwanbk** [comment]
> Will that stuff still be required once we switch to 0-Stor?

Yep.
Just wondering why it is not exist in the config file & etcd. Probably it is not needed to be there though, as myself also only setting it from command line

The main thing here is the tlog config example.

**Comment by GlenDC** [comment]
Well the config docs in master are up to date. @chrisvdg will have to up date the docs in his branch in #365 once he finished his code work. The file section of the main config docs contain all possible fields, so you'll see how to configure the tlogserver. Is blocked by the open PR to be finished and merged in your zerostor branch though.

**Comment by GlenDC** [comment]
Let's wait with this issue until the zerostor branch is ready for use. For now it is all still very much in flux, and I would like to see the "final" design before we work on this issue.

**Comment by GlenDC** [comment]
Is there still something here that you need to be done @iwanbk or can this issue be closed?

**Comment by iwanbk** [comment]
we can close it
