### ISSUE TITLE
fix race warning in vdisk_complete.go

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#379]
```
==================
WARNING: DATA RACE
Write at 0x00c42013362c by goroutine 11:
  internal/race.Write()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/sync/waitgroup.go:129 +0x14b
  github.com/zero-os/0-Disk/nbd/nbdserver.(*vdiskCompletion).Wait()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/vdisk_complete.go:14 +0x3e
  github.com/zero-os/0-Disk/nbd/nbdserver.testBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:107 +0x72f
  github.com/zero-os/0-Disk/nbd/nbdserver.TestBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:73 +0x410
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
Previous read at 0x00c42013362c by goroutine 114:
  internal/race.Read()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/sync/waitgroup.go:71 +0x26b
  github.com/zero-os/0-Disk/nbd/nbdserver.(*vdiskCompletion).Add()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/vdisk_complete.go:29 +0x43
  github.com/zero-os/0-Disk/nbd/nbdserver.(*backend).GoBackground()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend.go:223 +0x128
Goroutine 11 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
  testing.runTests()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/zero-os/0-Disk/nbd/nbdserver/_test/_testmain.go:78 +0x20f
t=2017-08-08T14:27:34+0000 lvl=info msg="vdisk 'a' received SIGTERM" module=global caller=backend.go:239
Goroutine 114 (running) created at:
  github.com/zero-os/0-Disk/nbd/nbdserver.testBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:86 +0x2a7
  github.com/zero-os/0-Disk/nbd/nbdserver.TestBackendSigtermHandler()
      /home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/nbdserver/backend_sigterm_test.go:73 +0x410
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
==================
```

**Comment by GlenDC** [comment]
I did have my questions with the design of this since the beginning, but at the time I didn't really see the reason why I had an issue with using WaitGroup as we did here. After reading through the docs I can see why it's a bad idea what we do here:


> > Note that calls with a positive delta that occur when the counter is zero must happen before a Wait. Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time. Typically this means the calls to Add should execute before the statement creating the goroutine or other event to be waited for. If a WaitGroup is reused to wait for several independent sets of events, new Add calls must happen after all previous Wait calls have returned. See the WaitGroup example.

> source: https://godoc.org/sync#WaitGroup

So basically we need to ensure that you can't still `Add` events, while you are already `Wait`ing, which is not something we ensue right now.

**Comment by iwanbk** [comment]
> After reading through the docs I can see why it's a bad idea what we do here:

> So basically we need to ensure that you can't still Add events, while you are already Waiting, which is not something we ensue right now.

From the WaitGroup docs, i can only see that it is buggy implementation, not bad idea, no?
Which after we  ensure that we can't `Add` after `Wait`, then it becomes good idea, no?

In fact, it was and still best idea, because there is no other idea :)

**Comment by GlenDC** [comment]
> it is buggy implementation

yes, I fixed it in my open WIP PR.

> it becomes good idea

It becomes a working implementation (I hope), as it seems to pass the tests now on my WIP PR, so I guess it does work now. Doesn't mean it becomes a good idea, but perhaps it is, I really have no idea or energy to think about that for now.
