### ISSUE TITLE
define statistics to log for milestone 8

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#386]
According to https://github.com/zero-os/home/blob/master/milestones/1.1.0-alpha-8.md we have to support among other things:

> Feed statistics into redis via core-0 statistics logging via stdout

What kind of statistics are we thinking about @zaibon? Please list all statistics required by creating the correct issues for them.

The actual implementation will be done using the solution for #385.

**Comment by zaibon** [comment]
Issue has been created at https://github.com/zero-os/0-Disk/issues/398
