### ISSUE TITLE
Feed statistics into ledis via core-0 statistics logging 

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-Disk#398]
Statistics that we need to provide to core-0 :

- [x] Vdisk iops read, format on logging `vdisk.iops.read@virt.vdiskid`
- [x] Vdisk iops write, format on logging `vdisk.iops.write@virt.vdiskid`
- [x] Vdisk throughput read in KB/s, format on logging `vdisk.throughput.read@virt.vdiskid`
- [x] Vdisk throughput write in KB/s, format on logging `vdisk.throughput.write@virt.vdiskid`

vdiskid need to be replaced by the actual ID of the vdisk.

Questions : Should we also add the cluster id to the statistics ?

**Comment by chrisvdg** [comment]
@zaibon , these are the keys for the statistics?

**Comment by zaibon** [comment]
Yes it is indeed. It's to be inline with the keys used by 0-core itself. See https://github.com/zero-os/0-core/tree/master/docs/monitoring#monitoring-metrics

**Comment by GlenDC** [comment]
> Should we also add the cluster id to the statistics ?

I don't think so, that's information that can be found based on timestamp and config, no?

**Comment by zaibon** [comment]
>Should we also add the cluster id to the statistics ?

Actually you should. Any information about the vdisk, cluster or anything that could be used for filtering should be added as a tag. These tags can then be used in grafana to make smarter graphs

**Comment by GlenDC** [comment]
This feature is finished and integrated in PR #429:

+ We use interval duration timers of 30 seconds. I think this is an OK balance between logging not too often, while still keeping those intervals regular enough to avoid too much irregularities between active and non-active switches;
+ Throughput aggregated values are protected against integer overflows by using the `math/big` package (this is only important during computations, the output value will always be small enough that it fits in a float32, in my tests those values are usually even < 125k);
+ IOPS values are small enough that they won't ever suffer from integer overflows during aggregation (int64 is big enough), but they are transformed into `big.Float` during computation just to ensure we get an as accurate output value as possible (once again the output value itself will be small enough that it fits in a float32, in my tests those values are usually even < 35k);
+ Values are logged even when 0;
+ IOPS values are well expressed in `N/s` (duh);
+ Throughput aggregate average value is expressed in `KiB/s`;
+ `cluster` is the metric-tags key for the primary cluster ID, and `templateCluster` is the metric-tags key for the template cluster ID, if such a template cluster ID is defined for the vdisk in question;

Will also update documentation (in `/docs`) and than I'll merge it into the alpha-8 and master branch.
