### ISSUE TITLE
tlogserver : handle flush/0-stor failure

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#399]
What we can do:

- [x] notify 0-orchestrator (#424)
- [x] client move to other server (already implemented)
- [x] server's vdisk stop itself (#448)

**Comment by iwanbk** [comment]
It seems the `zerostor` branch should at least `exit()`

**Comment by iwanbk** [comment]
> It seems the zerostor branch should at least exit()

will be done with #371

**Comment by iwanbk** [comment]
> What has to be done for a server's vdisk to restart itself? And what exactly do you mean with that @iwanbk?

It should be `stop` instead of `restart`. It might be ended up started again if the client reconnect again to this server.
It needs to : 
- kill all goroutine
- close all connected socket
- release other resource
There is unfinished work on `tlog-vdisk-stop-on-fail` branch.

**Comment by GlenDC** [comment]
Once this issue is resolved make sure to open a PR with the solution using [the 1.1.0-alpha-8 branch](https://github.com/zero-os/0-Disk/tree/1.1.0-alpha-7) as the base branch. Master is from now on meant for beta code.

**Comment by iwanbk** [comment]
all sub tasks has been implemented. closing it
