### ISSUE TITLE
slow 0-stor based tlog

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#404]
Did test to convert lede image to qemu image, as described in https://github.com/zero-os/0-Disk/issues/86#issuecomment-299135338.

It needs 4.5 mins

My last test using ardb based tlog finished in +- 20 seconds or +- 10 seconds (i'm pretty sure about 20 seconds, but not really sure about the 10 seconds).

So, 0-stor based tlog is at least 13x slower.

0-stor is indeed expected to be slower, but 13x is too much.

profiling result
[tlog-cpu.pdf](https://github.com/zero-os/0-Disk/files/1238011/tlog-cpu.pdf)

memory profiling result
[tlog-heap.pdf](https://github.com/zero-os/0-Disk/files/1238030/tlog-heap.pdf)

**Comment by iwanbk** [comment]
profiling result with JWT disabled  on 0-stor server,
[tlog-cpu-without-jwt.pdf](https://github.com/zero-os/0-Disk/files/1238104/tlog-cpu-without-jwt.pdf)

[tlog-heap-without-jwt.pdf](https://github.com/zero-os/0-Disk/files/1238105/tlog-heap-without-jwt.pdf)

**Comment by iwanbk** [comment]
commented 0-stor data & metadata operation, the performance is normal now.

**Comment by iwanbk** [comment]
Closing this issue because i did the test in wrong way

Just remember that because i don't have SSD, only HD, the test of ardb based tlog was using redis instead of ardb.

I redo the test, the 0-stor using tmpfs now, it is now finished in 39 seconds.
Still 2x-4x slower than the ardb one, but i think it is acceptable and could be optimized later

**Comment by GlenDC** [comment]
Not sure if that is acceptable though. The tlog was already "slow", having it now be 2x-4x slower, makes it really too slow imho...

**Comment by iwanbk** [comment]
>  makes it really too slow imho...

Yeah, indeed.

The bottleneck is in the 0-stor server which is out of my hand right now.

The good part is, we already know one of the slowness culprit, it is the JWT token validation.
https://github.com/zero-os/0-stor/issues/162
If i remove that part, the 0-stor version is faster than the ardb version.
