### ISSUE TITLE
Replace K and M names with the more informational Parity and Data names

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#411]
See https://github.com/zero-os/0-Disk/pull/400#discussion_r134596977 for more information and background for this issue.

Blocked by the merge of issue #400 into master.

**Comment by chrisvdg** [comment]
@GlenDC ,  is this only used for the tlogserver Config struct (and docs) or are there other structs/locations?

**Comment by iwanbk** [comment]
Also on tlog command line options

**Comment by GlenDC** [comment]
And also variables within the tlog module. If you decide to work on it @chrisvdg, make sure to assign yourself and put it in progress.
