### ISSUE TITLE
Look into FTPS support for backups

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#414]
Currently only plain FTP is supported for vdisk backup purposes. Look into supporting FTPS (FTP over TLS) as well.

**Comment by GlenDC** [comment]
If you have any questions @katia-e let me know here or via telegram.

**Comment by GlenDC** [comment]
> Shall the changed be defined in the same script storage_ftp.go

I think this makes the most sense. I would make it an optional field. Meaning you could for example make the `TLSConfig` an optional field, and when it is given TLS will be enabled using that config.

This makes the code also relatively simple, as well as easy to use. What I mean with that it will keep the API very small, making the module still small enough to learn how to use quickly. As you'll always want to keep an API as minimum as possible, without becoming too abstract.

What would `TLSMode` do? As I would have thought that a `TLSConfig` property would be enough as a pointer value. As a pointer value can just as well work for a boolean-type check.

**Comment by GlenDC** [comment]
@katia-e any progress on this issue?

**Comment by katia-e** [comment]
yes, @GlenDC, more questions:
Currently the ftp config is passed as a string. Should NewFTPStorageConfig have an additional optional input string that can be parsed into TlsConfig?
If tls.Config is specified, should we do the check if ftp server suports tls and if not, continue over plain ftp?

**Comment by GlenDC** [comment]
I just looked at the issue myself a bit:

+ I understand your question about TLSMode, I suppose you're talking about https://godoc.org/github.com/secsy/goftp#TLSMode, for now the default value for that is great. We can always expose that property later if needed, for now the default should be fine;
+ I don't think you want to expose another string value and parse that into a `tls.Config`, sounds like a bad idea.
+ If the user specified a TLS config (you'll still have to figure out what kind of flags you'll expose for this) than the creation of the (FTP) Storage Driver should fail in case the server does not support TLS. This is also the behavior of `secsy/goftp` as far as I've read through it, so that's good. Simply let the import/export command fail in that case, as we shouldn't try to open an insecure connection when the user specifically requested a secure connection.

The current API works pretty nice as it allows for one flag to be used for both the FTP and local driver, which makes it pretty user-friendly to use. However the API seems to break down as soon as you require a config which requires multiple flags (which I think is needed if you want to support optionally FTPS).

Perhaps you can make the current API work by adding a `*tls.Config` property to the `FTPStorageConfig` structure. However that will become ugly as:

+ That config is stored as an `interface{}` currently, so you would have to do a cast, which smells like bad design as this is cross-package casting, which is really asking for trouble;
+ Until now all properties were set by that one flag (string value), however suddenly you would start to get other properties (1 for now) that are set by the user on top of that, seems very confusing;

Perhaps a better idea might be to give up on the single flag idea, and instead provide a `-local` and `-ftp` flag. Only one of those flags should be specified at the same time. And if the `-ftp` flag is specified you could also check the other tls-related flags to see if they are given, and if so use them. Or perhaps you can still work with one `-storage` flag but somehow need to change the API around that, so that it's not all that magical and instead the config is still manually constructed so that you can easily also add other flags.

Learning to define great APIs is not easy, but it's important you learn to do this. Most of the work on this issue is in fact designing an API that allows this optional TLS configuration such that you can have FTP over TLS if wanted. Once you found a design that works, resolving the issue becomes very easy.

Feel free to DM me via telegram so we can quickly interact on it, if you feel you want to throw some ideas around. Certainly don't be afraid to play around with some different ideas.

**Comment by GlenDC** [comment]
You could use the following as inspiration on what you might want to expose as config in the backup module: https://github.com/go-openapi/runtime/blob/e8231e16de5bcda9839e03ae07c5c96a1fd82041/client/runtime.go#L38-L87

It's from another project that I now and than help co-maintain. As you can see it also supports the `InsecureSkipVerify` check. However, when that is defined we should really print out a big fat warning as `log.Info`, to warn that this is insecure and shouldn't be used in production.

So in way you could have the following TLS-related flags:

+ `--tls-cert cert`: certificate, can be given as a file or directly as text (*) (optional iff `--tls-insecure` is defined, otherwise required);
+ `--tls-key key`: key, can be given as a file or directly as text (*) (optional)
+ `--tls-ca ca`: always a file path, if not given we default to the system's default CA cert pool (optional);
+ `--tls-server server`: hostname/ip of the server that is used to validate the returned certificate (this is of course not done if the insecure option is disabled, but you don't need to do anything for that, all that is automatic based on the tls config) (optional);
+ `--tls-insecure`: flag to enable the insecure option (testing purposes only) (optional);

> (*) With this I mean is that you could try to first use the given string as a path, and try to read the file. If that returns an error indicating the file doesn't exist, than you can assume that it is a certificate instead and just pass that string directly to the backup TLS config. If that file does however exist and you can open it, than you would pass the content of that file to the config.

I hope this gives you some inspiration on how to solve the TLS config in backup module, and what extra flags we might need.

The only thing we would still need to define is how we'll deal with the already existing `--storage` flag. Either we keep it like that, or we change that a bit. We'll also need to think what to do with the existing `FTPStorageConfig` struct and how we would add this new TLS config to it, or how we would structure all that.

**Comment by GlenDC** [comment]
As I was afraid you might get a bit stuck because of how the design of the current code was, I opened a WIP PR #547, from which I suggest you continue working on this issue @katia-e (so just checkout this branch (`fix-414`) locally, so that you can continue working from it).

+ I moved the `StorageConfig` from the backup module to the zeroctl backup module as `storageConfig`. This way we can keep the one flag (`-s`/`--storage`) as it is quite practical, however it is very specialized for our zeroctl use-case, so there was in fact never a reason for it to be in the nbd backup module.
+ By removing the `NewStorageDriver` function  and `StorageConfig` structure, we clear up the backup module API a lot. And it makes it suddenly very clear how to come to a proper solution;

Further I renamed some structures to improve upon naming, and streamlined some stuff. I hope by doing this I unblock you on this issue. The following work is left to be done in order to make it functional:

+ Make sure to understand my changes, and why I did them;
+ Make sure to understand the relevant zeroctl parts and the FTP Storage code in the backup module as it is (as you'll see, I already provided the TLS support in the backup module, so you'll only need to work within the zeroctl code at this point);
+ You'll have to add the relevants tls flags to both the export-vdisk and import-vdisk commands:
   + When either the `--tls-insecure` or `--tls-certificate` is given, you'll want to create the `*backup.TLSConfig` and pass it into the `FTPStorageDriverConfig` (I added `TODO`s in the relevant locations for this);
   + When the `--tls-certificate` flag is given, the `--tls-key` flag has to be given as well;

If you want you could define a new flag type local to the zeroctl's `backup` module. This flag type would allow you to set a string directly as a string or via a given file path (which content you would read and use as the string instead). This new flag type would be used for both the `--tls-certificate` and `--tls-key` flag. This type would need to implement the following interface in order to use it as a flag `Var`: https://godoc.org/github.com/spf13/pflag#Value

After you did all this work (and you added the tests for this new flag type), you'll want to manually test to see if you can connect to an FTPS-enabled FTP server. You can first test while using the `--tls-insecure` flag, but afterwards I'll want you to test and verify that it works without defining the `--tls-insecure` flag (as this is what I would expect a user to use for production purposes.
