### ISSUE TITLE
tlog server : reuse canpn decoder

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#423]

**Comment by GlenDC** [comment]
Are you sure you want to do this for milestone-8? Seems like we can do this for beta-1, as there are still plenty of issues open related to tlog for milestone-8.

**Comment by iwanbk** [comment]
I have checked it a bit last week.
With current code, it is very easy to change the code to reuse capnp decoder. But i think it is not the point here.

The point is reusing the decoder's buffer. But simply calling `ReuseBuffer` in the end of loop is not working.

Because after decode, we hold the capnp object in memory.
Which means the buffer is indeed couldn't be reused because it is still in use.
