### ISSUE TITLE
a better approach for tlog client=>server commands

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#433]
Currently we only support TCP connections for communication between the tlogclient (used in tlog-supported vdisk's storages within the nbdclient) and tlogserver. The encoding protocol used for the messages transferred between client and server is Cap'n Proto. But while currently only TCP is supported, there is a feature open to also support the capnp-specialized RPC (see: #142). Currently that feature issue is still linked to the Roadmap milestone but I suggest to do it for the beta-1 milestone as it is a relatively small job to do, and it should improve the speed (as its specialized for capnp, so you would think that's the case, but benchmarking our end-to-end application will give us a more definitive answer I suppose).

Either way, when we support this RPC (alongside TCP support) is not something I want to tackle here, as that is something that can/should be discussed in the feature issue #142 itself. Instead I want to discuss the different kinds of messages which are send from client to server, and how the server knows which of message it receives and has to handle. All of this is happening after he handshake phase has taken place and both parties have confirmed they want to talk to each other.

# How it currently works

## Currently Support Messages

So what kind of messages do we currently send already, from client to server?

### Block Updates

```capnp
struct TlogBlock {
	sequence @0 :UInt64;
	index @1 :Int64;
	hash  @2 :Data;
	data @3 :Data;
	timestamp @4 :Int64;
	operation @5 :UInt8; # disk operation  1=OpSet,2=OpDelete
}
```

This is the most important kind of message as it is the sole reason the tlogserver exist, in order to process blocks and turn them into [aggregations][aggregation], in order to store them using [the 0-stor client][zerostorclient].

### Commands

```capnp
struct Command {
   type @0 :UInt8;        # command type
   sequence @1 :UInt64;   # sequence number
}
```

This is a type of message that can represent different kinds of messages depending on the value of the `type` property. All possible values of that property are defined by the following constants:

```go
const (
   MessageForceFlushAtSeq = 2  // force flush at sequence
   MessageWaitNbdSlaveSync = 3 // wait for nbd slave to be fully synced
)
``` 

The sequence property is not used for the `MessageWaitNbdSlaveSync`.

## How The Server Currently Handles Dynamic Messages

So how does the server currently handle the different kind of possible messages? Well it does so in very creative (*cough* hacky) way, by having the client write a message type directly to the TCP connection as a littleEndian binary value as follows:

```go
return binary.Write(w, binary.LittleEndian, mType)
```

I linked earlier the possible command types, well I didn't tell the whole truth. Those constant values are actually part of a Golang enum:

```go
// Type of message sent from client to server
const (
	messageTypeStart        = iota
	MessageTlogBlock        // tlog block
	MessageForceFlushAtSeq  // force flush at sequence
	MessageWaitNbdSlaveSync // wait for nbd slave to be fully synced
	messageTypeEnd
)
```

Thus for every post-handshake-phase message the client sends to the tlogserver, it first writes one byte of data which identifies the [Cap'n Proto][capnp] message it's about to send.

## Why the current approach is broken and should be replaced

In my humble opinion the current way we make the server distinguish between the different kind of message we want to send is a hack, which might have served us well so far, but wouldn't work any longer once we want to bring support for the [Cap'n Proto][capnp] RPC. Because using that we would need to communicate between the client and server using the Transport, provided and defined as follows:

```go
// godocs: https://godoc.org/zombiezen.com/go/capnproto2/rpc#Transport
type Transport interface {
    // SendMessage sends msg.
    SendMessage(ctx context.Context, msg rpccapnp.Message) error

    // RecvMessage waits to receive a message and returns it.
    // Implementations may re-use buffers between calls, so the message is
    // only valid until the next call to RecvMessage.
    RecvMessage(ctx context.Context) (rpccapnp.Message, error)

    // Close releases any resources associated with the transport.
    Close() error
}
```

And even if it somehow is possible to via another hacky approach still send custom binary data over the connection I don't think it would be good idea, but I doubt this is even possible. We could also use two different [Cap'n Proto][capnp] schemes, ones for TCP connections and one for the RPC connections, but that seems silly and only adds more code to maintain/worry about.

## A possible solution

Hence I would like to propose a scheme very similar as follows (which already includes some of the planned messages not yet supported, simply to showcase how all of them could be easily supported purely using the [Cap'n Proto][capnp] scheme language):

```capnp
# message to send from client to server
struct TlogClientMessage {
	union {
		Block @0 :TlogBlock;        # block message
		ForceFlushAtSeq @1 :UInt64; # force flush at seq message
		WaitNBDSlaveSync @2 :Void;  # Wait NBD Slave Sync message
		Disconnect @3 :Void;        # Disconnect message (see issue #426)
		StopNBDSlaveSync @4 :List(UInt64); # message to stop tlog from syncing
		                                   # (used for nbd self-healing open issues)
	}
}

# a tlog block
struct TlogBlock {
	sequence @0 :UInt64;
	index @1 :Int64;
	hash  @2 :Data;
	data @3 :Data;
	timestamp @4 :Int64;
	operation @5 :UInt8; # disk operation  1=OpSet,2=OpDelete
}

# Default Response from server to client
# used for:
#   + WaitNBDSlaveSync Message
#   + StopNBDSlaveSync Message
struct TlogDefaultResponse {
	status @0 :Int8;
}

# Response in case of a Flush from server to client
# used for:
#   + Block Message
#   + ForceFlushAtSeq Message
#   + Disconnect Message
struct TlogBlockResponse {
	status @0 :Int8;
	sequences @1 :List(UInt64);
}
```

I haven't played with this idea yet in the codebase itself so I'm not sure if the scheme above works as it is or needs some tiny modifications.

However after reading through https://capnproto.org/language.html#unions I'm fairly sure that this is the approach we want to go, as we can extend it in the future with as many possible messages as we want, without breaking out-dated clients. I hope that also means that it only takes as much space as it needs, and doesn't work like C unions work where it requires the space of the biggest possible union value. But from reading through the documentation that doesn't seem to be the case.

I hope we can go for this approach as it would make us stick to our encoding protocol, instead of doing some hacked combination of our own protocol on top of [Cap'n Proto][capnp]'s encoding protocol.

However if my proposal would not be good for whatever reason, and it can't be turned into a better proposal with some small tweaks. Than I hope that at least this is enough material to trigger a conversation about the current way we send messages from client to the tlogserver and how it can be done in a better way. Let's try to agree on a solution and go for it.

[capnp]: https://capnproto.org
[aggregation]: https://github.com/zero-os/0-Disk/blob/3049d4dbb3332f951e8c1c6d326f615e9d8e16de/tlog/schema/tlog_schema.capnp#L38-L46
[zerostorclient]: https://github.com/zero-os/0-stor/tree/master/client

**Comment by GlenDC** [comment]
@iwanbk I opened a PR where I implemented my proposal. This should also make it much easier to support RPC connections, alongside TCP connections. Why did we actually go for a TCP connection in the first place, I don't understand the choice instead of going for the RPC that comes with it.

I'm still not really happy with how responses are send, as for now we only have 1 kind of response possibility, which doesn't really make sense always. I also notice that for now we don't attach a unique ID to each message send, so at the moment it's not possible to link a response to a message either. Something we might want to think about in milestone-1.

Either way, this should make it fairly easy for me to support new commands, such as the `StopNBDSlaveSync` which will be used to stop 1 or multiple Slave Sync Server, rather than all of them. As we'll want to switch over in NBD in case of failure only to the ones needed, not the entire cluster. At least that's the current plan.

**Comment by iwanbk** [comment]
> Why did we actually go for a TCP connection in the first place, I don't understand the choice instead of going for the RPC that comes with it.

The reason because:
- we had a plan to move to dpdk, capnp rpc won't work over dpdk
- capnp rpc is not working on seastar C++ framework

**Comment by iwanbk** [comment]
>  which will be used to stop 1 or multiple Slave Sync Server, rather than all of them

Not sure what you mean by `Slave Sync Server`.
If it is the `slave syncer`, part of tlog which do the sync the to slave, then current command already only stop one slave syncer.

If it is ardb slave, then yes, it currently stop the sync to all ardb slave.

**Comment by GlenDC** [comment]
> If it is ardb slave, then yes, it currently stop the sync to all ardb slave.

Yes talking about ardb slave, and I don't think we'll ever want to stop syncing to all ardb slave at once.

> The reason because:
> + we had a plan to move to dpdk, capnp rpc won't work over dpdk
> + capnp rpc is not working on seastar C++ framework

I haven't heard about plans to move to seastar or dpdk in months, so I'm not sure if that's still a concern of ours.

**Comment by iwanbk** [comment]
> I haven't heard about plans to move to seastar or dpdk in months, so I'm not sure if that's still a concern of ours.

Yeah, me too.

We already use seastar btw

**Comment by GlenDC** [comment]
> We already use seastar btw

Where? Certainly not in 0-Disk o.O

**Comment by iwanbk** [comment]
> Where? Certainly not in 0-Disk o.O

Well, i thought you could already guess it, it is C++ framework, so the only one can use it is the old C++ tlog server

**Comment by GlenDC** [comment]
.......... But that repo is dead? Why would I guess that? I thought it was there just for historical reasons.

**Comment by iwanbk** [comment]
Hmm... i think i need to say 

> The reason was because

instead of 

> The reason because

When answering this question.

> Why did we actually go for a TCP connection in the first place, I don't understand the choice instead of going for the RPC that comes with it.

So, the reason to use TCP was because of dpdk & seastar things :)

**Comment by GlenDC** [comment]
Yeah sure I got that. So I don't see a reason why we're still using TCP even though we're clearly not using dpdk or seastar. Not that I have experience with capnp's RPC, but if we're using capnp for encoding purposes anyhow, might as well use its RPC...

Anyway, that was like a minor question in the original issue report, so let's not keep going back and forward about that one in this issue, as there is already an issue open for that one (issue #142).
