### ISSUE TITLE
make tlog tests work without need for iyo env variables

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#457]
Currently one cannot run any tests which create a 0-stor client, without defining _valid_ values for the three `iyo` variables: `iyo_organization`, `iyo_client_id` and `iyo_secret`.

0-Stor seems to use a PEM certificate and public key for this, as can be seen in:
+ https://github.com/zero-os/0-stor/blob/master/client/client_test.go#L27
+ https://github.com/zero-os/0-stor/blob/master/client/client_test.go#L68

That could be a solution. Either way, we need something so travis and developers can run tests again without requiring to set environment variables.

**Comment by GlenDC** [comment]
@zaibon were you able to take a look at this?

**Comment by zaibon** [comment]
Not yet
