### ISSUE TITLE
add 'zeroctl import template' command

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-Disk#460]
We need a command to be able to import a template vdisk from the 0-hub to a local storage cluster.

**Reason for that are:**
1. For the restore vdisk to work properly, we need to also have tlog data for templates vdisk. Currently during the command `copyvdisk` from the hub to a local storage cluster when creating a new boot disk, all the data of the templates are sent to the tlog. So the tlog then has all the data he needs to rollback a vdisk. This process is extremely slow and costly. 
2. Seamlessly importing a template vdisk of a windows machine won't work with 4k block used in boot vdisks. So we need to download the template to the locale storage cluster when installing an environment. 

**Proposed solution:**
During the installation of an environment and after the storage cluster has been deployed. We will import all the templates we want to have available in this environment from the 0-hub. During this process, the tlog data will be created for each local template disk. Thanks to this, we can now create new boot vdisk fast again. The only thing needed then is to copy the metadata of the template vdisk and add a reference to the tlog data. Both actions shouldn't be long to execute.

This flow also solve the windows template problems since the import of template can takes some time, it's not a problem.

**Command interface**:

```
zertctl import template templateid dst_clusterid
```

**Comment by iwanbk** [comment]
>  The only thing needed then is to copy the metadata of the template vdisk and add a reference to the tlog data.

Because we use double linked list for tlog metadata, we also need to copy the metadata.
(double linked list has `prev` and `next` pointer).

We can only `fork` the metadata if it is backward list

**Comment by FastGeert** [comment]
For the 0-Disk suite a template does not really exist. Its just another vdisk that can be copied. Templates are an orchestrator concept.
