### ISSUE TITLE
generate tlog data when importing a vdisk (from a backup)

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#466]
When importing a vdisk from a (FTP) backup currently we only generate storage data.

However in case that vdisk is configured with tlog support, and also has a tlogclustered configured for it, we should also generate tlog data, I think.

This will make importing a vdisk slower, but I think we have no other choice, as otherwise the tlog feature for that vdisk will be useless, as a restore would remain with partial results until all indices that were available since the import were overridden.

This might be able to utilize the tlog generator written as part of the PR #453, but I'm not too sure.

**Comment by GlenDC** [comment]
@zaibon can you confirm that this is indeed a feature that is required, and/or your opinion on this?

**Comment by zaibon** [comment]
@GlenDC  We will indeed need to somehow regenerate the tlog data otherwise we won't have any restore feature.
Now is it going to be faster to recreate the tlog data from scratch during import. Or to also save tlog data in the backup and just importing it?

**Comment by GlenDC** [comment]
Not sure, I wouldn't even know how we would export it, that hasn't been included in the design. Not even sure if that would serve any purpose. We wouldn't even know if we're importing using the same vdiskid as we used for exporting or not. Unless we start saving such metadata as well. But I don't think we're supposed to also backup the tlog chain...

**Comment by zaibon** [comment]
Ok then, let's go for the solution where we re-create tlog data during import then. 
How much impact on the speed of the import do you think this will have ?

**Comment by GlenDC** [comment]
> How much impact on the speed of the import do you think this will have ?

Not sure, that would be a question @iwanbk might be able to answer.

**Comment by iwanbk** [comment]
> Ok then, let's go for the solution where we re-create tlog data during import then.
> How much impact on the speed of the import do you think this will have ?

Similar to the new `zeroctl copy` i guess
