### ISSUE TITLE
tlogserver syncs to primary cluster instead of slave cluster

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#475]
While working on the self-healing storage code (with all the consequences it has for primary, slave and template cluster), I was going once again through the tlog code, this time focussing a bit more on the slave sync code.

Here I noticed that the code which is responsible for keeping the slave cluster in sync with the data the tlogserver has is writing to the primary cluster instead of the slave cluster.

Here is a break down of the current code:

In [`tlog/tlogserver/slavesync/slave_sync.go#L121-L127`](https://github.com/zero-os/0-Disk/blob/196c18e382ae839c9fee9bca457bea49890539ce/tlog/tlogserver/slavesync/slave_sync.go#L121-L127) we create a `tlog.Player`:
```go
func (ss *slaveSyncer) init() error {
	// tlog replay player
	player, err := player.NewPlayer(ss.ctx, ss.configSource, ss.apc.VdiskID, ss.apc.PrivKey, ss.apc.DataShards, ss.apc.ParityShards)
	if err != nil {
		return err
	}
	ss.player = player
// ..
```

This is used to write data to an internal blockstorage which is created as part of the `NewPlayer` logic using the given `ss.configSource`. This can be seen in [`tlog/tlogclient/player/player.go#L33-L66`](https://github.com/zero-os/0-Disk/blob/master/tlog/tlogclient/player/player.go#L33-L66):
```go
// ...
       // get config to create block storage
	vdiskCfg, err := config.ReadVdiskStaticConfig(source, vdiskID)
	if err != nil {
		return nil, err
	}
	nbdCfg, err := config.ReadNBDStorageConfig(source, vdiskID, vdiskCfg)
	if err != nil {
		return nil, err
	}

	// create static provider,
	// as the tlog player does not require hot reloading.
	ardbProvider, err := ardb.StaticProvider(*nbdCfg, nil)
	if err != nil {
		return nil, err
	}

	blockStorage, err := storage.NewBlockStorage(storage.BlockStorageConfig{
		VdiskID:         vdiskID,
		TemplateVdiskID: vdiskCfg.TemplateVdiskID,
		VdiskType:       vdiskCfg.Type,
		BlockSize:       int64(vdiskCfg.BlockSize),
	}, ardbProvider)
// ...
```

Thus you can see that the provider is created in the `ardb.StaticProvider` constructor using the given `nbdConfig` (which contains all clusters), for the used internal block storage in that player.

+ That static provider is as it says static and does not support hot-reloading, this is bad as this player is in this instance used throughout the entire lifetime of a tlogserver-vdisk object, and thus even if the config is updated in its lifetime, it won't be updated;
+ But this isn't even the issue I would like to address here. The real issue is that it will create a provider using the Primary Cluster, and if supported even template cluster. The slave cluster will never be used and data will be written to the Primary Cluster, to which the nbdserver is also writing;

This can be seen in [`nbd/ardb/provider.go`](https://github.com/zero-os/0-Disk/blob/196c18e382ae839c9fee9bca457bea49890539ce/nbd/ardb/provider.go):

```go
// StaticProvider creates a Static Provider using the given NBD Config.
func StaticProvider(cfg config.NBDStorageConfig, pool *RedisPool) (ConnProvider, error) {
	if pool == nil {
		pool = NewRedisPool(nil)
	}


	provider := &staticRedisProvider{redisPool: pool}
	provider.setConfig(&cfg)
	return provider, nil
}

// ...

func (rp *staticRedisProvider) setConfig(cfg *config.NBDStorageConfig) {
	rp.dataConnectionConfigs = cfg.StorageCluster.DataStorage
	rp.numberOfServers = int64(len(rp.dataConnectionConfigs))

	rp.metaConnectionConfig = cfg.StorageCluster.MetadataStorage

	if cfg.TemplateStorageCluster == nil {
		rp.templateDataConnectionConfigs = nil
		rp.numberOfTemplateServers = 0
	} else {
		rp.templateDataConnectionConfigs = cfg.TemplateStorageCluster.DataStorage
		rp.numberOfTemplateServers = int64(len(rp.templateDataConnectionConfigs))
	}
}
```

As you can see no Slave Cluster is used or accesses anywhere, it only deals with Primary and Template clusters.

So that's an issue as the tlogserver should sync data to the slave cluster, not the primary cluster. On top of that the configuration should support hot reloading as the config might be updated over the course of its life time.

**Comment by iwanbk** [comment]
> That static provider is as it says static and does not support hot-reloading, this is bad as this player is in this instance used throughout the entire lifetime of a tlogserver-vdisk object, and thus even if the config is updated in its lifetime, it won't be updated;

This is not a problem (at least in old slave syncer). In old slave syncer (with file based config), slave syncer will be restarted on SIGHUP.

**Comment by GlenDC** [comment]
> This is not a problem (at least in old slave syncer). In old slave syncer (with file based config), slave syncer will be restarted on SIGHUP.

But as far as I can see it's a problem now. Either way, the real problem that this issue is addressing is that we are syncing data to the primary storage instead of the slave storage.

**Comment by iwanbk** [comment]
> But as far as I can see it's a problem now and not handled

yeah, true, the code indeed not maintained anymore since the disable and i saw a lot of discussion to rework it.
Will try to fix it after the main problem in this issue solved

>  Either way, the real problem that this issue is addressing is that we are syncing data to the primary storage instead of the slave storage.

from my quick read, current `DynamicProvider` and `StaticProvider` can't use slave storage. Do i missed something or should we use another struct?

**Comment by GlenDC** [comment]
No you don't miss anything. But that should have been a problem obvious when implementing it...

For now there is nothing you can do on this issue @iwanbk as it's blocked by work I have to do regarding the self-healing stuff. Once the metadata server is removed from 0-Disk, and the storage cluster states have been implemented (with the new code), it should be more obvious hopefully what to do with this issue.

**Comment by iwanbk** [comment]
> For now there is nothing you can do on this issue @iwanbk as it's blocked by work I have to do regarding the self-healing stuff. Once the metadata server is removed from 0-Disk, and the storage cluster states have been implemented (with the new code), it should be more obvious hopefully what to do with this issue

For the real issue (write to primary instead of slave) i think i don't need to wait for your work on self healing. And i think we need to fix it sooner than later.

From my code reading, what we need to do are:
1) add slave storage to `DynamicProvider` and `StaticProvider`
2) configure the tlog player to use slave storage instead of primary when being used by slave syncer.

Let me know if there are other changes i need to do, especially related to point (1)

**Comment by GlenDC** [comment]
Obviously you could do that, the solution you propose is quite straight forward.

I just said, it doesn't really matter as I'm fairly sure those providers will no longer be part of the new design. So your work would simply be thrown away. All it would do is fix this issue, which would anyhow get fixed as part of the new design...

So with that in mind, while you could easily fix this issue by adding slave storage (and it would't really be that simple, what you really would want is use slave cluster as the primary cluster for the tlog player), I'm fairly sure there are better ways to spend your valuable time.
