### ISSUE TITLE
zeroctl copy requires tlog config when parity and data shards args are not passed

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#478]
There was an optional arguments was added to `zeroctl copy vdisk` command `parityShards` and `dataShards`. I understand when they're provided `zeroctl` try to copy tlog data but when they're not provided the `zeroctl copy` only copies the metadata, it should not require tlog config as far as I understand

**Command:**  `/bin/zeroctl copy vdisk —config 10.105.3.11:2379 template:ubuntu-1604 vdisk2 st`

```
t=2017-09-19T09:47:04+0000 lvl=info msg="parsing positional arguments..." module=global caller=vdisk.go:48
t=2017-09-19T09:47:04+0000 lvl=info msg="generating tlog data for target vdisk `vdisk2`" module=global caller=vdisk.go:108
t=2017-09-19T09:47:04+0000 lvl=eror msg="key 'vdisk2:vdisk:conf:storage:tlog' was not found on the ETCD server" module=global caller=source_etcd.go:63
t=2017-09-19T09:47:04+0000 lvl=eror msg="received invalid etcd config 'vdisk2:vdisk:conf:storage:tlog' (vdisk:'')" module=global caller=source_etcd.go:151
{"status":403,"subject":"etcd","data":{"endpoints":["10.105.3.11:2379"],"key":"vdisk2:vdisk:conf:storage:tlog"}}
Error: failed to create tlog generator: failed to create flusher: config is not available in source
Usage:
  zeroctl copy vdisk source_vdiskid target_vdiskid [target_clusterid] [flags]

Flags:
      --config SourceConfig   config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)
      --data-shards int       data shards (K) variable of erasure encoding (default 4)
  -h, --help                  help for vdisk
  -j, --jobs int              the amount of parallel jobs to run the tlog generator (default 16)
      --parity-shards int     parity shards (M) variable of erasure encoding (default 2)
      --priv-key string       private key (default "12345678901234567890123456789012")
      --same                  enable flag to force copy within the same nbd servers

Global Flags:
  -v, --verbose   log available information

failed to create tlog generator: failed to create flusher: config is not available in source
```

**Comment by iwanbk** [comment]
please update to last master.

If you don't want to also copy tlog data, please make sure you don't have tlog cluster configured for the target vdisk

**Comment by khaledkbadr** [comment]
By tlogcluster configured you mean `{vdiskid}:vdisk:conf:storage:tlog`?

**Comment by iwanbk** [comment]
> By tlogcluster configured you mean {vdiskid}:vdisk:conf:storage:tlog?

Not sure, i mean it should doesn't have `tlogServerClusterID` as described below
```yaml
vdisks:
  myimg:
    blockSize: 4096
    readOnly: false                    
    size: 10 
    type: boot
    nbd:
      storageClusterID: mycluster
      #tlogServerClusterID: main
```

**Comment by iwanbk** [comment]
the fix is on `fix-copyvdisk-alpha-8`, could you try it?

**Comment by iwanbk** [comment]
has been fixed in  alpha-8 branch

**Comment by khaledkbadr** [comment]
Looks like the new addition checks on the value of `tlogServerClusterID` not just the existence of the key

When I had this config 

```
vd6:vdisk:conf:storage:nbd
storageClusterID: myblockcluster
templateStorageClusterID: 87ec688e821f5f0006619b7207d656bd
tlogServerClusterID: ''
```

It only copied the metadata and skipped the tlog data and when I used random data in the value
```
vd7:vdisk:conf:storage:nbd
storageClusterID: myblockcluster
templateStorageClusterID: 87ec688e821f5f0006619b7207d656bd
tlogServerClusterID: 'dfadsdsafa'
```

It worked

**Comment by GlenDC** [comment]
@khaledkbadr your last comment doesn't make any sense. If in your last example `dfadsdsafa` does not exist, than you shouldn't be able to boot up vdisk `vd7` at all, due to an invalid config.

> It only copied the metadata and skipped the tlog data

Isn't that what you want? You want it to not try to generate tlog data in case you didn't specify the tlogServerClusterID, no? Or am I missing something here?

**Comment by khaledkbadr** [comment]
> than you shouldn't be able to boot up vdisk vd7 at all, due to an invalid config.

It started copying the vdisk without any errors for sometime, anyway I don't think we use `tlogServerClusterID` value in any way in the `zeroctl copy` since we don't have any tlogservers running. On the other hand `{vdiskid}:vdisk:conf:storage:tlog` will have correct configuration in there which will allow the copying of tlog data.

> Isn't that what you want?

Yup exactly, but to allow the other behavior which will allow me to copy the tlog data I have to put a value that I don't have `tlogServerClusterID` value at that stage. Hence, I fixed it by putting "temp" to that value and it wont effect anything either way. 

Anyway, It's tested with the "temp" value for both behaviours (copying metdata only, and copying metadata+tlog data)

My question then, does it make sense that I have to add that random string to the key?

**Comment by iwanbk** [comment]
> My question then, does it make sense that I have to add that random string to the key?

random value is working because `zeroctl copy` doesn't use tlog server at this stage

**Comment by GlenDC** [comment]
> random value is working because zeroctl copy doesn't use tlog server at this stage

Ooooh right, a random value does work as long as you never try to actually read that value. But please don't ever add a random value, as this will trigger tlog to be used and thus operations will/should fail.

So if you don't want/have a tlogServerCluster, than don't specify the `TlogServerClusterID` either (or give explicitly the empty string value).

**Comment by khaledkbadr** [comment]
> please don't ever add a random value, as this will trigger tlog to be used and thus operations will/should fail.

It's alright actually, I override that config with the proper config when I create a VM. So tlogServerCluster will be correct when it's being used

> So if you don't want/have a tlogServerCluster, than don't specify the TlogServerClusterID either

I already do that :)

BTW, feel free to close this issue since it's been tested by QA. and @iwanbk can you notify me when this is fixed on master so I can update our flist

**Comment by GlenDC** [comment]
Fixed by PR #479.

**Comment by GlenDC** [comment]
Not sure why this was assigned to alpha-8, but OK I merged it into master as well using a merge commit 1641c88659b7915192079a0b86ce9a8cdfa35209 (@iwanbk could you review this merge commit, as there was a merge conflict and I moved your logic to the `tlog/copy` module).

@khaledkbadr, you should be able to get latest master and have this fix.

**Comment by iwanbk** [comment]
>  but OK I merged it into master as well using a merge commit 1641c88 (@iwanbk could you review this merge commit

It failed on travis, looks like conflict with recent changes about IYO variables.
https://travis-ci.org/zero-os/0-Disk/jobs/277611980
```
invalid ZeroStorClusterConfig: Org: non zero value required;;Org: non zero value required;;
```

I actually already prepared another PR for the master #480

**Comment by GlenDC** [comment]
> It failed on travis, looks like conflict with recent changes about IYO variables.

I'm already fixing that travis fail.

> I actually already prepared another PR for the master #480

Ah sorry, wasn't clear to me from this issue. Please next time link to this issue and communicate about it.
