### ISSUE TITLE
redesign ardb provider/cluster code

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#483]
The current design of how we interact with storage clusters via structures such as the ardb.Provider has been outgrown, and it will be good that for issue #455 and other (self-healing) storage issues, to have a shiny new redesign for it.

Currently:

+ There is no mention of states in the cluster/ardb conn/provider code, there is only a concept of one being disabled or not;
+ It is not possible to get just the server config for a given index, rather than also an entire new open connection on top of it;
+ It is unclear if the template should still be part of a cluster, or can just be used in-code as a secondary primary cluster, which has no slave cluster linked to it;
+ MetadataConnection is still part of the provider interface even though there is no seperate metadata server anymore since PR #482 (right now we simply return the first available server, but it is unclear if this still belongs in that interface or not);
+ It is not easily possible to create an ardb provider which uses the slave cluster as the primary cluster (which is needed for the tlog slave_sync feature);

And there might be some more things wrong in the current design, that prevents us from adding some needed features and fix some open bugs. But this is what I know from the top of my hat.

This issue can be and probably should be worked together on with issue #455.

**Comment by zaibon** [comment]
> MetadataConnection is still part of the provider interface even though there is no seperate metadata server anymore since PR #482 (right now we simply return the first available server, but it is unclear if this still belongs in that interface or not);

I don't think we need this part of the interface anymore, as long as the spreading logic for metadata is the same as for data, I don't see the benefit of having 2 method that does the same things.

**Comment by GlenDC** [comment]
> I don't think we need this part of the interface anymore, as long as the spreading logic for metadata is the same as for data, I don't see the benefit of having 2 method that does the same things.

Not all metadata is spread, as it simply doesn't make sense for some stuff, this is the case where the metadata is simply 1 "value":

+ Semideduped storage has a bitmap which it stores as a single value in metadata, so for that simply the first available storage is used for now;
+ Storages which have tlog-support enabled and configured store the last flushed (tlog) sequence in the internal storage also as a single value in the first available storage for now;

For both these cases spreading is not really possible unless you would start to store it in all data servers, but that would be not very efficient at all. On top of that none of these cases I just mentioned are actually critical, as in the vdisk (which owns that metadata) would still function fine even if those would get lost, it would simply give us a hit in performance (temporarily).
