### ISSUE TITLE
zeroctl copy fails if nr of servers was wrong but after the tlog data was copied

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#501]
I've tried to copy vdisk but with different template and storage cluster number of servers, as expected it raised `target data server count has to equal the source data server count`. But that happened after all the tlog data has been copied. It should fail at the start

**Comment by GlenDC** [comment]
Yes, you are right. We should copy the metadata first, and only than copy the tlog data.

**Comment by GlenDC** [comment]
Fixed in `1.1.0-alpha-8` branch in commit 1814605.

Merged into master in commit 93875d7.
