### ISSUE TITLE
Metadata of an exported vdisk should contain vdisk blocksize and size properties

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-Disk#509]
Currently the vdisk blocksize and size properties must be supplied at the import from the ftp server. If eg an incorrect blocksize is passed, or a size that is smaller than the partitions / filesystems in the vdisk, that will lead to errors.

**Comment by GlenDC** [comment]
+ what you need to supply as a flag to the import command is `-b`/`--blocksize`, but that is the block size of the exported blocks, nothing to with vdisks. However I agree that we could write this in metadata of a backup if you want (would make already made backups unusable though);

That being said...

+ A snapshot (exported) vdisk is completely decoupled from any vdisk. It does not store any information besides its blocks. Meaning you can import it as the same vdisk but also any other vdisk;
+ The vdisk's `blocksize` and `size` are supplied in the same way as they are supplied to the nbdserver, via the `etcd` config, so I don't get how this could ever be different than that of your actual vdisk, as it's in fact the config of the actual vdisk...
+ Storing such vdisk data would make our backup zeroctl commands a lot less powerful, as now your snapshot would only be usable by vdisks with those same properties, while now you can can export a vdisk of any `blocksize,` and import them as a vdisk of any (other) block size;
+ I don't know why you are bringing up `size` as no zeroctl command uses `size` at all, that's a property only used by the `nbdserver`;

**Comment by FastGeert** [comment]
Export / import is being used for backup / restore, but also for adding images to what we call the vdiskstorage.
See:
* [import image](https://rawgit.com/zero-os/0-orchestrator/master/raml/api.html#vdiskstorage__vdiskstorageid__images_post)
* [create vdisk](https://rawgit.com/zero-os/0-orchestrator/master/raml/api.html#vdiskstorage__vdiskstorageid__vdisks_post)

I don't want to build in restrictions of any kind into the zeroctl commands, but I want to prevent people from making mistakes. For the import action, they should not need supply the blocksize for the resulting image. This can only lead to errors. Same applies for the size of the image, and the bootdisks that are copied from it, they cannot be smaller.

**Comment by GlenDC** [comment]
Ok as discussed:

+ We'll store all kind of metadata related to the source disk for a snapshot made:
  + (when overwriting a snapshot, this metadata will also be overwritten);
  + this will be anything related to the source vdisk which might be useful: vdiskID, Size, BlockSize and Type;
  + this information will however not be enforced by the zeroctl toolsuite, and is only meant for extra information for those who care about it;
+ However:
  + we will validate that `the total snapshot data size (blockCount * blockSize)` does not exceed the size of the vdisk we wish to import (see issue #510);
  + we will provide a new command `zeroctl describe snapshot`, which will allow to read this extra information in `JSON` format (see issue #511);

**Comment by GlenDC** [comment]
In issue #511 you can find the properties that need to be stored under some metadata key as part of the deduped map of a snapshot. Makes me think that deduped map is also a bad name, and perhaps we better call it something like (snapshot) header.
