### ISSUE TITLE
Rollback: using timestamp `0` does not rollback the disk to latest as expected

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-Disk#513]
Using a `0` timestamp does not rollback the disk to latest transaction as expected.

**Comment by iwanbk** [comment]
More info from telegram chat

```
Muhamad Azmy, [02.10.17 13:51]
@zaibon when i did a rollback to 'now' timestamp the machine booted again

Muhamad Azmy, [02.10.17 13:51]
so apparently it's the rollback to '0' that is broken
```

The odd thing here : when user specify `0` as the `--end-timestamp`, the player will replace it with current timestamp.

**Comment by GlenDC** [comment]
Are you guys talking about the same timestamp. What timestamp do you mean @muhamadazmy when you talk about `now`? and What timestamp do you talk about @iwanbk when you say current timestamp? Please be more specific and technical at all times... This tends to give communication problems if you're not careful.

**Comment by GlenDC** [comment]
@muhamadazmy I tried to restore by the way without giving any timestamp (and thus having 0 for both begin and ending):

```
zeroctl restore vdisk lede --parity-shards 1 --data-shards 1
```

and that restore works for me.

So are you sure that you are not really doing something wrong OR facing a bug not related to the timestamp at all?

**Comment by GlenDC** [comment]
@muhamadazmy @iwanbk any more progress on this issue, or can it be closed as `wontfix`?

**Comment by muhamadazmy** [comment]
@GlenDC Sorry for the late response. 
We were trying the built in rollback feature of zero-disk to redistribute the keys on the available ardbs when one of the master ardbs is gone forever. So for example, if the ardb cluster consists of 4 nodes, and one is gone, we want to replay the entire tlog server for (all) vdisks to the latest point in time (now) so the rollback will rewrite the blocks back to the remaining 3 nodes. Of course the broken node was already marked as disabled. 

According to @zaibon we should use timestamp `0` which means replay to the end of the tlog. But testing with this timestamp didn't produce the expected results.

I am not sure if this still a valid issue, this was like 26 days ago. Also rollbacking to timestamp `now` works fine.

**Comment by GlenDC** [comment]
But even at the time of reporting this issue both @iwanbk and me tested with timestamp `0`, and that worked just fine as it was back then.

I'll close it for now, feel free to re-open if you think the issue you had was a problem in 0-Disk that's still in there.

**Comment by muhamadazmy** [comment]
@GlenDC sure, thanks for your time.
