### ISSUE TITLE
tlog: false error logging when disconnecting client and server

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#522]
It seems that when the tlogclient disconnects from the tlogserver, we get at some point an `io.EOF`  error in the tlogclient receiver at:

https://github.com/zero-os/0-Disk/blob/314316585ce1d4201c7b8cd1a2fc913e17d5b868/tlog/tlogclient/client.go#L222-L226

This logs an error now, even though an `io.EOF` at the point of disconnecting ourselves is quite acceptable. So I think: 

+ we either somehow filter `io.EOF` away in case we triggered the disconnect ourself, but that seems error prone;
+ or a perhaps better idea would be that we ensure that we close that goroutine before we start disconnecting our connection with the server, such that it will never receive the `io.EOF` when we disconnect on purpose ourselves;

This bug doesn't cause any issues I think, but it's confusing to see a logged error, when really that seems to be just expected behavior.

I do not think we can simply ignore the `io.EOF` error, as it would indicate an error in case this happens because the server disconnects before we want so.

**Comment by GlenDC** [comment]
I think a different issue but for now I don't know if it's a bug or not, is that I also get from that same log line, when stopping a qemu-system emulation: a `use of closed network connection` error. Not sure if that's just another error type used for a connection that is closed, or if this actually indicates a bug where we were still trying to read replies from the server but couldn't any longer?

**Comment by iwanbk** [comment]
> or if this actually indicates a bug where we were still trying to read replies from the server but couldn't any longer?

It is persistent connection, so the client trying to read from socket continuously.

At this stage, it could be:
- some error in the network
- the server indeed close the connection

One thing for sure, i don't understand why it becomes a bug.
But yes, logging it as error is sometimes not appropriate

**Comment by iwanbk** [comment]
Just realized the title, the error is not returned, it is just logged

**Comment by GlenDC** [comment]
Well of all types of bugs it's the least bad one to have. I rather have false negatives than false positives, that's for sure. But still, it's confusing and if possible there should be no error log at all there.

> some error in the network

Yes because `io.EOF` could also be because of some error in the network. I think it would be the easiest solution, if possible, to exit such receiver goroutines right before we disconnect, as at that point we shouldn't receive anything anymore anyhow, as we have no more connection. Another possibility would be to have some state, and know that in this state we don't have to care about `io.EOF`, but that is more of an ugly solution imho, as it would force us to check such a variable at all times...

**Comment by iwanbk** [comment]
just to make sure, your point is the logging, right?
Because both cases (network error & server closes the connection) already handled

**Comment by GlenDC** [comment]
Yes, my point is the logging. But you cannot just remove it, as there are scenarios where `io.EOF` at that location _is_ an error that should be notified.
