### ISSUE TITLE
tlog : sync with other active tlog server

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#527]
We already have support for multiple tlog servers, but only one tlog server active at a time.

We have situation where we have two active tlog servers for same vdisk, in limited amount of time. 

The scenario is Live Migration:

```

nbdserver1, tlogserver1 = before migration starts, they will go away after migration
nbdserver2, tlogserver2 = after migration, they will continue after migration

step                    | host w                | host x      | host y            | host z
------------------------+-----------------------+-----------------------------------------
before migration status | qemu1, nbdserver1     | tlogserver1 | nbdserver2        | tlogserver2 (idle) listening to tlogserver1
                        |                       |             |                   | waiting for taking over 
------------------------+-----------------------+-------------+-------------------+-------
migrating status        | qemu1 waits for sync  | tlogserver1 | qemu2, nbdserver2 | tlogserver2 (idle) listening to tlogserver1
                        | from nbdserver1, then |             |                   | waiting for taking over 
                        | switches to qemu2 on  |             |                   |
                        | host y                |             |                   |
------------------------+-----------------------+-------------+-------------------+-------
after migration         |                       | tlogserver1 | qemu2, nbdserver2 | tlogserver2 takes over                  
                        |                       | flushes last|
                        |                       | block and   |
                        |                       | notifies    |
                        |                       | tlogserver2 |
                        |                       | to take over|
```

In this scenario, both tlog servers could be active but there is **only one** that can do the flush at a time.

### coordination between tlog servers
TSX = tlog server X
NBDX = NBD server X

**migrating status**
TS2 connect to TS1.
TS2 can safely take over and do flush if failed to connect to TS1

**after migration**
0-orch send SIGTERM to NBD1 and then TS1.
TS2 detect that TS1 is down, TS2 can take over and do the flush

## what TS1 need to do
simply open a TCP listener (for TS2 to open TCP socket) or HTTP server (for TS2 to poll).
tcp socket seems to be more efficient but HTTP is easier to use and has more builtin error handling.
polling in this case also not really bad:
- for limited amount of time
- only one connection from TS2

## what TS2 need to do
- open tcp socket or do http poll to TS1, as described in "coordination" section
- hold all flush until meet one of these conditions:
     - detect that TS1 dies
     - ~~reach timeout  (configurable)~~ (see comment from @FastGeert below)
     - ~~reach X number of transactions (configurable)~~ (see comment from @FastGeert below)

- load last sequence from 0-stor
- if needed, rewrite the sequence number of all received blocks
- after take over, inform NBD2 to use new "last sequence". As temporary solution, TS2 could use response from TS2 to NBD2 to inform the new last sequence

**Comment by FastGeert** [comment]
@iwanbk would not do any polling
when t1 is done, it should send "go:<last sequence number>" to t2 and close the tcp socket. Then t2 can take over without needing to go and catch the last sequence number from the backend

@iwanbk why would this not be good for permanent solution?

@iwanbk why do you think we might need a timeout of x number of transactions, because that could screw things up, no?

**Comment by iwanbk** [comment]
> @iwanbk would not do any polling

OK, i don't have  strong opinion on polling as well.

> when t1 is done, it should send "go:" to t2 and close the tcp socket. Then t2 can take over without needing to go and catch the last sequence number from the backend

OK, we can do it as well for optimisation.
But we still need to handle the case where the connection simply closed, right?
Never assume that network is reliable.

> @iwanbk why would this not be good for permanent solution?

About below things, right?
" As temporary solution, TS2 could use response from TS2 to NBD2 to inform the new last sequence"

It might become permanent solution, just not sure this time

> @iwanbk why do you think we might need a timeout of x number of transactions, because that could screw things up, no?

Because everything could happen in networking system. But yeah, it should never happen except for some silly reason TS1 stopped to work but still keep network connection to TS2.
We can of course set the timeout and number of transaction to high value.

**Comment by FastGeert** [comment]
> But we still need to handle the case where the connection simply closed, right?
Never assume that network is reliable.

yes good thinking

> Because everything could happen in networking system. But yeah, it should never happen except for some silly reason TS1 stopped to work but still keep network connection to TS2.
We can of course set the timeout and number of transaction to high value.

Then its better that the migration fails. Otherwise we risk dataloss

**Comment by iwanbk** [comment]
> OK, we can do it as well for optimisation.
> But we still need to handle the case where the connection simply closed, right?
> Never assume that network is reliable.

Also to handle case where TS1 failed to send it's last message to TS2.
And then TS2 failed to reconnect to TS1 because it already dies.

> Then its better that the migration fails. Otherwise we risk dataloss

OK, agree

**Comment by iwanbk** [comment]
> after take over, inform NBD2 to use new "last sequence"

It is not as simple as i thought yesterday.
The problem is we could have many transactions in buffer, which we need to update as well.
I still can't find a good way to do it, because the buffer producer and consumer working in async way using goroutines.

We can't simply increase the sequence number in server - side because other than sending block, we have other commands which rely on sequence number.

**Comment by iwanbk** [comment]
Ah OK, i just found a simple solution to fix in-nbd-buffer transactions.

After receiving new sequence from server, nbd could send command to tlog client to "fix" the sequence number for range of sequences.

I think it will work, but i do admit that it is not a clean solution.

**Comment by FastGeert** [comment]
@GlenDC what are your thoughts on this?

**Comment by iwanbk** [comment]
> After receiving new sequence from server, nbd could send command to tlog client to "fix" the sequence number for range of sequences.

We still have problem with blocks that in transition between:
- nbd - tlogclient
- tlogclient - tlogserver

It might be a sign that this whole idea is not a good idea.

On the other hand, @FastGeert new idea to hold of any write operation seems to be a much better idea.
But from a quick look at the nbd code, i think it is better to not hold write operation, but holding sending write transactions to tlog server

**Comment by FastGeert** [comment]
Proposed test scenario:
```python
// it tests the idea described at  https://github.com/zero-os/0-Disk/issues/527#issuecomment-334711480
// Test scenario :
// - create 0-stor clusters
// - create nbdserver 1 (nb1) and tlogserver 1 (t1)
// 		- t1 listen at coordListenAddr
// - create nbd2 & t2 with same vdisk
//		- t2 need to wait for t1
//		- t2 use same 0-stor cluster as t1
// - nbd1 write X data and send "sync"
//		- then flush it
// - as soon as nbd1 "sync" returns, nbd2 write Y data
// 		- then flush it
// - stop nbd1 & t1
// - write some more to nbd2
// - stop nbd2 & t2
// - verify that tlog has X+Y data with correct sequence
```
