### ISSUE TITLE
improve error code in 0-Disk

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#529]
The error code in 0-Disk is already better than it used to be. For example right now we already return error types or "constant" errors, where it makes sense, such that the callee can check if an error is of that type or is equal to that "constant".

Great, but there can still be improved upon the error code:

+ It is not uncommon that we want to do multiple things which all return errors. However we want to do all actions regardless if one or multiple of those actions return an error. The result is thus some kind of list. For now in all these scenarios we make some quick error type ourselves right now;
+ We often wrap errors in order to give more context, and while this is great it does make us lose the original error;

What we're trying to solve in this issue is not a unique problem.

A package like [`github.com/pkg/errors`](https://github.com/pkg/errors) comes to mind, but there might be others. Perhaps we need one or perhaps we need multiple. Or perhaps we need to define some common primitives ourselves. Either way, it could use some improvement.

**Comment by GlenDC** [comment]
What we probably want is:

+ Be able to group non-related errors together into one error (as described above);
+ Be able to add context to another error (as described above), as a smarter way of wrapping around it;
+ Avoid the use of `fmt.Errorf` errors where possible, as we now use them way too much imho;
+ Add more "constant" errors where they make sense, as well as error types where those make sense;
+ All these features can be provided by using one or multiple dependencies, and/or providing our own `github.com/zero-os/0-Disk/errors` package for capabilities we want to share with the entire codebase;

A first good steps would probably be go through the entire codebase to see where and how we return errors at the moment, do error handling, and where we could use the improvements mentioned above (or not).

In order to avoid making this into too big of a PR at once, you could classify the improvements, such that you can do one thing at a time. Such that you can open one smaller PR at a time, where you fix one class of improvements at a time.

It's an issue that covers really a lot of ground, so feel free to DM me on telegram or ask more questions here before you start on it, or while you're working on it.

**Comment by GlenDC** [comment]
If you want a quick video-call about this, let me know and we can do it tomorrow if so.

**Comment by chrisvdg** [comment]
@GlenDC , sure, let me know when you're available!
