### ISSUE TITLE
add testable (godoc) examples for ardb package

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#543]
add missing reply examples to `reply_test.go`: https://github.com/zero-os/0-Disk/blob/df57a5623e5442559a30e112a5507413c2e58d09/nbd/ardb/reply_test.go#L295-L298

- [x] `ExampleError`
- [x] `ExampleBytes`
- [x] `ExampleOptBytes`
- [x] `ExampleInt64`
- [x] `ExampleInt64ToBytesMapping`

add missing cluster examples to `cluster_test.go`: https://github.com/zero-os/0-Disk/blob/df57a5623e5442559a30e112a5507413c2e58d09/nbd/ardb/cluster_test.go#L13-L16

- [x] `ExampleNewCluster`
- [ ] <s>`ExampleNewClusterPair`  </s>

**Comment by chrisvdg** [comment]
@GlenDC , what does `ExampleNewClusterPair` have to show specifically?

**Comment by GlenDC** [comment]
> what does ExampleNewClusterPair have to show specifically?

Nevermind that one, it doesn't exist anymore (for the time being). It might exist again once we figured out the entire primary-slave stuff, but for now it's non-existent.
