### ISSUE TITLE
add `--version` flag to nbdserver and tlogserver

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#556]
Add a flag `--version` to both the `nbdserver` and `tlogserver` executables, such that when that flag is given it will print the version information and exit _instead_ of starting the server. The version information is expected to be given in the following format:

```
Version: 1.1.0-beta-1
Build: 36b6ffb 2017-10-20T17:01:00-0500
Runtime: go1.9.1 darwin
```

As inspiration, check out: https://github.com/zero-os/0-Disk/blob/acd1e3b477f1cc9ce244c2a8a3875dcacaca7788/zeroctl/cmd/version.go#L11-L46

(feel free to refactor this outputVersion logic into a function `PrintVersion`, specified in `0-Disk/version.go`, as we can than use the same logic for all 3 executables)

The build information is optional and is given by the Makefile, by having it specify the `CommitHash` and `BuildDate` variables. Therefore you'll also have to adapt the Makefile, such that when building `nbdserver` and `tlogserver` we also give that information.

**Comment by iwanbk** [comment]
I think it will be nice to also print this version information each time nbd & tlog started, without the need to specify the flag.

**Comment by GlenDC** [comment]
I suppose that could be nice for logs. I'll make another issue for it.
