### ISSUE TITLE
add version property to metadata of snapshots (vdisk backups)

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#574]
When creating a backup we also store some metadata. All that info can be retrieved for a snapshot using the `zeroctl describe snapshot` command. For example:

```
$ zeroctl describe snapshot bar_1508696133 --pretty
{
  	"snapshotID": "bar_1508696133",
  	"blockSize": 131072,
  	"size": 14024704,
  	"created": "2017-10-22T13:15:33-05:00",
  	"source": {
  	  	"vdiskID": "bar",
  	  	"blockSize": 4096,
  	  	"size": 10737418240
  	}
}
```

So the main 5 properties right now that we have are `snapshotID`, `blockSize`, `size`, `created` and `source`. The only required ones are `snapshotID`, `blockSize` and `size`.

What I would like is to have a 6th property added, `version`. Such that the command above would give the following output instead:

```json
{
  	"snapshotID": "bar_1508696133",
  	"blockSize": 131072,
  	"size": 14024704,
  	"created": "2017-10-22T13:15:33-05:00",
        "version": "1.1.0-alpha-8",
  	"source": {
  	  	"vdiskID": "bar",
  	  	"blockSize": 4096,
  	  	"size": 10737418240
  	}
}
```

This property is also optional (for backwards compatibility reasons), and it can be assumed that the version is `"1.1.0"` when not given. As that is the semver in which the entire versioning was added.

The goal of this version is that if in the future for some reason we would have some breaking change or some new functionality, we could check the version (and compare it with `zerodisk.CurrentVersion`) to remove any ambiguity and do different things based on those comparisons.

As part of this issue you'll have to do the following:

- [x] Add `func VersionFromString(string) (Version, error)` to `github.com/zero-os/0-Disk/version.go`;
  + when the given string is empty it can be assumed that the version is `1.1.0` (make a private var for this);
- [x] Add an example for the new `VersionFromString` func;
- [x] Add unit tests for the new `VersionFromString` func;
- [x] Add a new optional `Version` (`string`) property to the `Metadata` struct of the `ardb/backup` module (make sure to document that this is the version of the toolchain);
  + make sure to validate the version in the `(*Header).Validate` method;
- [x] Modify the backup code such that it properly supports this new `Version` property;
- [x] Add the new optional `Version` (`string`) property to `SnapshotInfo` struct of the `zeroctl describe command` code (don't forget the `omitempty` annotation);
- [x] Support this new optional `Version` property in the `zeroctl describe command` code;

**Comment by muhamadazmy** [comment]
Working on https://github.com/zero-os/0-Disk/tree/snapshot-version

**Comment by muhamadazmy** [comment]
@GlenDC 
I am almost done with this feature request, except i have questions about 2 bullets in the tasks list.
- The example usage of `VersionFromString` func, how and where exactly this should be done?
Also the sub point, make sure to validate the version int he (*Header).Validate method, but this is already done by the validator annotation, right? i mean there is no need for actual code to do this.

**Comment by muhamadazmy** [comment]
Nevermind the question about the `example` task, I added an Example test for VersionFromString.

**Comment by GlenDC** [comment]
> Also the sub point, make sure to validate the version int he (*Header).Validate method, but this is already done by the validator annotation, right? i mean there is no need for actual code to do this.

Wrong. That would be true if the bencode package supported an Umarshaler/Marshaler interface that we could use for a custom backup-version type. That's something I did propose in the  `github.com/zeebo/bencode`package, but so far no reaction from the maintainer.

However, even if we had those interfaces, it would still not be done automatically, the validation code would just be moved to the `UnmarshalBencode` function, rather than the `Validate` function.

Right now we store the version in our header as a string. Which is fine. However, when we read a header, it would be good to ensure that this header value is valid (note that it's optional, so it's ok that this value is empty). To ensure it's valid you could keep it as simple as `if _, err := zerodisk.VersionFromString(header.Version); err != nil { /* oops, an error */ }`.

But right now you have no validation, which is not good. So please resolve that as well as part of your PR #577.
