### ISSUE TITLE
ardb become in failed state once it failed to write to

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#611]
While working on `handle-ardb-crash` branch as part of #491, i found that primary ardb become failed once we failed to write to that ardb.

It seems to be by design, as pointed by @zaibon at https://github.com/zero-os/0-Disk/issues/541#issuecomment-344534724.

However this design prevent us to do this simple recovery case:
- stopping ardb
- starting ardb again

Those two actions simulate these cases:
- temporary network error
- ardb failed temporary
- ardb crash, but then restarted again -> not really sure about this case, orchestrator might never restart crashed ardb server

It seems that we can recover using the same ardb server by doing these:
- create another storage cluster, but with same ardb
- change the storage cluster ID of the nbdserver to the new created storage cluster

Except for "temporary network error" case, it seems to be OK for simplicity reason.
If there is any of it, docs behind this design decision will be helpful

Another question is, do we have assumption that storage network is always reliable?

**Comment by zaibon** [comment]
I don't think this is something we should try to recover in any sort of way. If we fail to write there is a problem. And the normal self-healing flow should take care of fixing it.

If in the future we notice that some network glitch or other create false positive and the ardb server are actual still up and running when we detect write error. then we could still improve the retry mechanism somehow, but let's not try to fix things that we don't know if it will even happens.

**Comment by GlenDC** [comment]
@iwanbk there is no self-healing code in place in your branch or in master. Neither are there even states. So what you're looking at is really not a representation of what is planned to be done.

See https://github.com/zero-os/0-Disk/blob/master/specs/ardbfailurescenarios.md for more information.

**Comment by iwanbk** [comment]
> Neither are there even states. 


https://github.com/zero-os/0-Disk/blob/master/nbd/ardb/storage/cluster.go#L257-L261

> So what you're looking at is really not a representation of what is planned to be done.
> 
> See https://github.com/zero-os/0-Disk/blob/master/specs/ardbfailurescenarios.md for more information.

OK, thx
