### ISSUE TITLE
Document future concept of t-log module

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-Disk#620]
Create a document explaining philosophy, goals, features and methods of the transaction server from the conceptual viewpoint.

### Goal: 
The document is meant to summarize the current vision of the future t-log module architecture. This document will be used to define necessary changes in current version and guide actual implementation.

### Source: 
The document is based on the recording of the meeting from 15.11.17

**Comment by GlenDC** [comment]
This issue was posted in the wrong repository and has been moved to https://github.com/zero-os/0-tlog/issues/4.
